"""規劃覆蓋表：plan-tree-nodes.json 的 495 個節點 + 規劃 1.1／2.x 的共通機制。

每一列都必須有 status / where / note，缺一個就讓建置失敗（build_v03.write_plan_coverage）。

status 只有四種：
  IMPLEMENTED      已落地，where 是「腳本:函式」或「PERK EDID + 進入點」
  PENDING-round2   機制前線第二輪（大地、風、鮮血、神聖）——round 2 之後為 0
  PENDING-round3   機制前線第三輪（毒素、水、黑暗、星界）——round 3 之後為 0
  DEFERRED         有具體技術理由不能完成，note 寫清楚是什麼理由

round 3 收尾後 NODES 必須涵蓋全部 495 個節點：rows() 不再給任何樹預設狀態，
缺一個就讓 build_v03.write_plan_coverage 以 SystemExit 失敗。

節點鍵：(樹 id, 路線 0-2, 階 0-4, 'M' 或 'B0'..'B3')。
"""
from __future__ import annotations

ROUND1_TREES = ['common', 'noform', 'fire', 'frost', 'lightning']
ROUND2_TREES = ['earth', 'wind', 'blood', 'divine']
ROUND3_TREES = ['poison', 'water', 'darkness', 'astral']

IMPL = 'IMPLEMENTED'
R2 = 'PENDING-round2'
R3 = 'PENDING-round3'
DEF = 'DEFERRED'

# 本輪共用的延後理由：玩家「被打」的事件目前沒有掛勾（PO3 OnHit / OnMagicHit on player alias）。
NO_PLAYER_HIT = ('玩家受擊事件尚未掛勾（PO3 OnHit/OnMagicHit on player alias）；'
                 '與土樹岩甲「被打 -1」同一個缺口，統一在 round 2 開一個 ESSBGuard 別名腳本接上')

# ------------------------------------------------------------------ 節點表（round 1 的五棵樹）
NODES = {
    # ================= 5.2 全元素通用（tree 12）
    ('common', 0, 0, 'M'): (IMPL, 'ESSBNodes.SyncThresholdScale → ESSBController.SyncStage', '同調門檻 -2%／點，下限 0.4 倍'),
    ('common', 0, 0, 'B0'): (IMPL, 'ESSBNodes.CarryOverSync → ESSBController.SwitchForm', '承接：切換保留前一形態 1/3 同調'),
    ('common', 0, 1, 'M'): (IMPL, 'ESSBNodes.CommonHitMult', '同調二段時附傷 +1%／點'),
    ('common', 0, 1, 'B0'): (IMPL, 'ESSBController（同調只在切換與關閉時歸零）', '不移：本模組本來就不因打斷或擊倒扣同調，分支是行為保證，不另加事件'),
    ('common', 0, 1, 'B1'): (IMPL, 'ESSBNodes.SyncThresholdScale + ESSBController.FormHeldSeconds', '專一：同形態 60 秒後門檻再 ×0.5'),
    ('common', 0, 2, 'M'): (IMPL, 'PERK ESSB_P_common_0_2_M<n> 進入點 0x24（受到的傷害）', '同調三段時受傷 -0.5%／點，條件 GetGlobalValue(ESSB_SyncStage) >= 3'),
    ('common', 0, 2, 'B0'): (IMPL, 'ESSBNodes.SelfSlowImmune', '定神：守衛函式已落地，目前唯一的自我減速來源是冰原，風/土的在 round 2/3 接上'),
    ('common', 0, 3, 'M'): (IMPL, 'ESSBNodes.CommonHitMult', '同調三段時重擊附傷 +2%／點'),
    ('common', 0, 3, 'B0'): (IMPL, 'ESSBController.OnWeaponHit（ExtremeCount）', '極致：同調三段每 10 次命中多一次全額附傷'),
    ('common', 0, 3, 'B1'): (IMPL, 'ESSBNodes.OnSyncStage', '回饋：升段回復生命與魔力各 B_max ×2'),
    ('common', 0, 4, 'M'): (IMPL, 'ESSBNodes.AvatarCooldown → ESSBController.Tick → ESSBElem.OnAvatar', '化身：同調三段每 30-<點數> 秒觸發當前元素的持續傳奇效果'),
    ('common', 0, 4, 'B0'): (IMPL, 'ESSBNodes.HasPerpetual → ESSBController.OnFormClosed', '永續：三段時融斷後保留一段同調'),
    ('common', 1, 0, 'M'): (IMPL, 'ESSBNodes.CommonHitMult', '所有元素附傷 +1%／點'),
    ('common', 1, 0, 'B0'): (IMPL, 'ESSBNodes.HasWideMark → ESSBController.AfterOpen', '廣印：開印擴散到附近 1 人'),
    ('common', 1, 1, 'M'): (IMPL, 'ESSBNodes.MarkDurationBonus → ESSBController.ApplyMark', '印記持續 +0.2 秒／點'),
    ('common', 1, 1, 'B0'): (IMPL, 'ESSBController.ToggleForm + PERK ESSB_P_common_1_1_B1 進入點 0x24', '順轉：免魔力門檻；切換後 1 秒受傷 -50%（讀 ESSB_GuardSwitch）'),
    ('common', 1, 1, 'B1'): (IMPL, 'ESSBNodes.OpenSyncBonus → ESSBController.AfterOpen', '先制：開印 +2 同調'),
    ('common', 1, 2, 'M'): (IMPL, 'ESSBNodes.OpenSyncBonus', '開印 +1 同調／每 5 點'),
    ('common', 1, 2, 'B0'): (IMPL, 'ESSBController.OnValidHit（RegElem2 副印記）', '雙印：新元素進副格、較舊的留主格，不觸發終焉；融斷時兩格各結算一次'),
    ('common', 1, 3, 'M'): (IMPL, 'ESSBNodes.CommonHitMult', '所有元素附傷再 +1%／點'),
    ('common', 1, 3, 'B0'): (IMPL, 'ESSBNodes.OpenStrikeMult → ESSBController.ApplyProc', '深印：開印那一擊附傷 ×1.5'),
    ('common', 1, 3, 'B1'): (IMPL, 'ESSBNodes.OnFormOpened', '臨界：開形態時附近敵人減速 30% 2 秒'),
    ('common', 1, 4, 'M'): (IMPL, 'ESSBNodes.StatusCapBonus → ESSBController.StackCap', '每種元素狀態上限 +1／每 5 點，最多 +3；量表類不吃'),
    ('common', 1, 4, 'B0'): (IMPL, 'ESSBNodes.OmniMult', '萬象：層數效果 +25%（熱度附傷、爆燃每層、流血與毒層 DoT）'),
    ('common', 2, 0, 'M'): (IMPL, 'ESSBNodes.CommonEndMult', '終焉 +1%／點'),
    ('common', 2, 0, 'B0'): (IMPL, 'ESSBNodes.EchoRatio → ESSBController.OnWeaponHit', '餘響：切換後首次命中附帶前一元素 50% 附傷'),
    ('common', 2, 1, 'M'): (IMPL, 'ESSBNodes.CommonBurstMult', '融斷 +1%／點'),
    ('common', 2, 1, 'B0'): (IMPL, 'ESSBNodes.OnEndReward', '反哺：每次終焉回魔 B_max'),
    ('common', 2, 1, 'B1'): (IMPL, 'ESSBController.EndMark（RegElem2 + RegSecondUntil）', '疊印：終焉後舊印記留 4 秒副印記，融斷再結算一次'),
    ('common', 2, 2, 'M'): (IMPL, 'ESSBNodes.EchoRatio', '切換後首次命中附帶前一元素附傷 +3%／點'),
    ('common', 2, 2, 'B0'): (IMPL, 'ESSBNodes.HasChainEnd → ESSBReactions.ChainEnd', '連鎖終焉：附近同印記目標也終焉 ×0.5，abChain 防遞迴'),
    ('common', 2, 2, 'B1'): (IMPL, 'ESSBNodes.TrioMult → ESSBController.PushTrio', '三重奏：10 秒內三種元素終焉，第三次 ×3 並保留全部同調'),
    ('common', 2, 3, 'M'): (IMPL, 'ESSBNodes.CommonEndMult', '終焉再 +1%／點'),
    ('common', 2, 3, 'B0'): (IMPL, 'ESSBNodes.ConcertMult → ESSBController.TakeSwitchEnd', '協奏：切換後首次終焉 ×1.5'),
    ('common', 2, 3, 'B1'): (IMPL, 'PERK ESSB_P_common_2_3_B2 進入點 0x24', '安全閥：融斷時受傷 -50% 2 秒（讀 ESSB_GuardBurst）'),
    ('common', 2, 4, 'M'): (IMPL, 'ESSBNodes.CommonBurstMult', '融斷再 +2%／點'),
    ('common', 2, 4, 'B0'): (IMPL, 'ESSBNodes.HasGrandConcert → ESSBReactions.ChainEnd', '大協奏：切換後首次終焉讓範圍內同印記各終焉一次'),
    ('common', 2, 4, 'B1'): (IMPL, 'ESSBNodes.HasTwin → ESSBController.OnWeaponHit（GetEquippedWeapon(true) 比對 akSource）', '雙生：左手武器攜帶前一形態元素 30 秒'),

    # ================= 5.1 無元素（tree 11）
    ('noform', 0, 0, 'M'): (IMPL, 'PERK ESSB_P_noform_0_0_M<n> 進入點 0x23（武器傷害）', '無形態時武器傷害 +1%／點，條件 ESSB_FormActive == 0 且無下一階'),
    ('noform', 0, 0, 'B0'): (DEF, 'PERK ESSB_P_noform_0_0_B1（目前無進入點）', '穩步：格擋耐力消耗在本機 Skyrim.esm 裡找不到對應的原版進入點用例，索引無法實測確認；需進遊戲以 CK 進入點清單逐一試'),
    ('noform', 0, 1, 'M'): (IMPL, 'ESSBNoForm.OnMartialHit', '重擊碎甲：自有減防 1%／點 5 秒'),
    ('noform', 0, 1, 'B0'): (IMPL, 'ESSBGuard.OnHitEx（abHitBlocked）→ ESSBController.SetRiposte', '反擊：格擋成功後 3 秒內下一次命中附傷 ×1.3；round 2 接上 PO3 OnHitEx 後結清'),
    ('noform', 0, 1, 'B1'): (IMPL, 'PERK ESSB_P_noform_0_1_B2 進入點 0x1B（重擊耐力）×5', '疾攻：條件 ESSB_Combo >= 1..5，每段 ×0.9（乘法疊加，約 -41%）'),
    ('noform', 0, 2, 'M'): (IMPL, 'ESSBNoForm.OnMartialHit', '暴擊率 +1%／點，自有擲骰，命中補一次武器基準的真實傷害'),
    ('noform', 0, 2, 'B0'): (IMPL, 'ESSBNoForm.OnCombo → ESSBController.OnNoFormHit', '節奏：4 秒內 3 次命中回耐力並 +1 戰意'),
    ('noform', 0, 3, 'M'): (IMPL, 'PERK ESSB_P_noform_0_3_M<n> 進入點 0x23 ×5', '戰意每層武器傷害 +0.5%／點，條件 ESSB_Resolve >= 1..5'),
    ('noform', 0, 3, 'B0'): (IMPL, 'ESSBNoForm.OnMartialHit', '破勢：碎甲持續 5 → 8 秒'),
    ('noform', 0, 3, 'B1'): (IMPL, 'PERK ESSB_P_noform_0_3_B2 進入點 0x24', '不屈：戰意 ≥3 時受傷 -10%'),
    ('noform', 0, 4, 'M'): (IMPL, 'ESSBNoForm.OnMartialHit（真實傷害路徑）', '終結：戰意滿層重擊「無視護甲 +3%／點」改以等量真實傷害表達，見實作紀錄的偏離說明'),
    ('noform', 0, 4, 'B0'): (IMPL, 'ESSBNoForm.OnMartialHit', '處決：戰意滿層重擊對 <25% 生命目標補 ×2 真實傷害並清空戰意'),
    ('noform', 1, 0, 'M'): (IMPL, 'ESSBNoForm.OnManaBreak', '破魔：削魔 5+1／點、等量回魔、削減量 ×比例的真實傷害、破魔印 8 秒'),
    ('noform', 1, 0, 'B0'): (IMPL, 'ESSBNoForm.OnManaBreak', '蝕魔：削魔量取「固定值」與「目標最大魔力 2%」的高者'),
    ('noform', 1, 1, 'M'): (IMPL, 'ESSBNoForm.OnManaBreak', '真實傷害比例 +3%／點，上限 0.95'),
    ('noform', 1, 1, 'B0'): (IMPL, 'ESSBNoForm.IsCasting + ESSBController.TakeInterrupt', '斷咒：GetAnimationVariableBool(IsCasting*) 判定，清空魔力 + 1 秒沉默代替硬直，5 秒一次'),
    ('noform', 1, 1, 'B1'): (IMPL, 'ESSBGuard.OnHitEx（akSource 是 Spell）', '反噬：受到法術傷害時回魔 B_max ×G(L_無元素)，每攻擊者 3 秒一次'),
    ('noform', 1, 1, 'B2'): (IMPL, 'ESSBCounter.OnAnimationEvent → ESSBNoForm.OnCounterSpell', '反咒：破魔印上註冊 MRh/MLh_SpellFire_Event，讀該手裝備法術的有效魔力消耗 ×(1+0.02×L)'),
    ('noform', 1, 2, 'M'): (IMPL, 'ESSBNoForm.ApplySilence → ESSBController.ApplySilenceSpell', '沉默 1 + 0.2／點秒（上限 4），首領減半'),
    ('noform', 1, 2, 'B0'): (IMPL, 'ESSBNoForm.OnManaBreak', '枯竭：目標魔力已為 0 時，真傷改以你當前魔力 5% 計'),
    ('noform', 1, 2, 'B1'): (IMPL, 'ESSBNoForm.OnManaBreak（ESSB_Silence keyword）', '靜寂：沉默中目標受真傷 ×1.5'),
    ('noform', 1, 3, 'M'): (IMPL, 'ESSBNoForm.IsSpellUser', '對施法者／帶 MagicArmorSpell／MagicCloak 的敵人削魔量 +5%／點'),
    ('noform', 1, 3, 'B0'): (IMPL, 'ESSBGuard.OnHitEx + PERK ESSB_P_noform_1_3_B1 進入點 0x29', '破護：認出「來源是法術、無投射物、攻擊者帶原版 MagicCloak」那一跳，開 2 秒「受到的法術強度 ×0」視窗並逐跳刷新；第一跳仍會吃到，理由見實作紀錄'),
    ('noform', 1, 3, 'B1'): (IMPL, 'SPEL ESSB_Ability_AntiMagic + ESSBController.RefreshAbilities', '抗咒：無形態時掛上魔抗 +15 的自有常駐能力，開形態即移除'),
    ('noform', 1, 4, 'M'): (IMPL, 'ESSBNoForm.TrueMult', '目標魔力 <25% 時本樹傷害 +3%／點'),
    ('noform', 1, 4, 'B0'): (IMPL, 'ESSBNoForm.OnKill → ESSBController.Tick', '無魔：擊殺施法者回滿耐力與魔力'),
    ('noform', 1, 4, 'B1'): (IMPL, 'ESSBController.ApplyTrueDamage', '逆流：真實傷害的 50% 轉為你的生命'),
    ('noform', 1, 4, 'B2'): (IMPL, 'ESSBNoForm.ApplySilence', '封印：沉默改為 3 公尺範圍（最多 5 人，規劃 2.9）'),
    ('noform', 2, 0, 'M'): (IMPL, 'ESSBNoForm.BurstMult', '融斷 +2%／點'),
    ('noform', 2, 0, 'B0'): (IMPL, 'ESSBNoForm.OnBurst → ESSBController.ToggleForm', '免門檻：融斷後下一次開形態不檢查魔力（ESSB_FreeOpen）'),
    ('noform', 2, 1, 'M'): (IMPL, 'ESSBNoForm.EmberRatio → ESSBController.OnNoFormHit', '餘燼：關形態後 10 秒內無形態命中附帶前一元素附傷 +2%／點'),
    ('noform', 2, 1, 'B0'): (IMPL, 'ESSBNoForm.BurstRadius', '收束：融斷範圍 15 → 20 公尺'),
    ('noform', 2, 1, 'B1'): (IMPL, 'ESSBNoForm.OnBurst', '餘燼延續：餘燼 10 → 20 秒'),
    ('noform', 2, 2, 'M'): (IMPL, 'ESSBNoForm.BurstRadius', '融斷範圍 +0.3 公尺／點'),
    ('noform', 2, 2, 'B0'): (IMPL, 'ESSBNoForm.OnBurst → ESSBController.SetSyncKeep', '連斷：融斷後 5 秒內重開形態保留一半同調'),
    ('noform', 2, 3, 'M'): (IMPL, 'PERK ESSB_P_noform_2_3_M<n> 進入點 0x23', '淬火：融斷後 10 秒內武器傷害 +1%／點（讀 ESSB_Quench）'),
    ('noform', 2, 3, 'B0'): (IMPL, 'ESSBNoForm.OnBurstTarget', '斷界：融斷後對範圍內敵人上減速 30% + 碎甲 10%，3 秒'),
    ('noform', 2, 3, 'B1'): (IMPL, 'ESSBNoForm.OnBurst', '回流：融斷每個印記回魔 B_max ×0.5'),
    ('noform', 2, 4, 'M'): (IMPL, 'ESSBNoForm.BurstMult', '融斷再 +3%／點'),
    ('noform', 2, 4, 'B0'): (IMPL, 'ESSBNoForm.OnBurst → ESSBController.OnFormOpened', '雙斷：融斷後 3 秒內再開形態，對範圍內敵人各開印一次'),

    # ================= 5.3 火焰（tree 0）
    ('fire', 0, 0, 'M'): (IMPL, 'ESSBElem.FireHitMult', '熱度每層火附傷 +（8% + 0.2%／點）'),
    ('fire', 0, 0, 'B0'): (IMPL, 'ESSBElem.HeatCap → ESSBController.StackCap → ESSBStatus.AddStack', '添薪：熱度上限 10 → 15，自燃跟著改在 15 層'),
    ('fire', 0, 1, 'M'): (IMPL, 'ESSBElem.FireHitMult', '火附傷 +1%／點'),
    ('fire', 0, 1, 'B0'): (IMPL, 'ESSBElem.HitStacks', '烙印：重擊熱度 +2 → +4'),
    ('fire', 0, 1, 'B1'): (IMPL, 'SPEL ESSB_Ability_WarmBlood + ESSBController.RefreshAbilities', '溫血：火形態時掛 StaminaRateMult +20 的自有能力'),
    ('fire', 0, 2, 'M'): (IMPL, 'ESSBElem.ApplyFireResistShred', '帶熱度目標火抗 -1%／點（自有 FireResistDebuff，6 秒）'),
    ('fire', 0, 2, 'B0'): (IMPL, 'ESSBElem.IgniteResidual', '熔心：自燃後熱度保留一半'),
    ('fire', 0, 2, 'B1'): (IMPL, 'ESSBElem.HasMoltenBody → ESSBController.AddSelf/TickTimers + PERK ESSB_P_fire_0_2_B2 進入點 0x24', '熔身：過熱滿改為 10 秒熔身（火附傷 +100%、受傷 -20%、每秒回耐力 5、過熱不累積）'),
    ('fire', 0, 3, 'M'): (IMPL, 'ESSBElem.FireHitMult', '同調每段火附傷 +1%／點'),
    ('fire', 0, 3, 'B0'): (IMPL, 'ESSBGuard.OnHitEx', '灼身：被近戰命中時攻擊者熱度 +1 並受一次 B_max ×1.0 火傷，每攻擊者 3 秒一次'),
    ('fire', 0, 3, 'B1'): (IMPL, 'ESSBElem.OnIgnite', '火浴：自燃時回血 B_max ×2'),
    ('fire', 0, 4, 'M'): (IMPL, 'ESSBElem.IgniteMult', '業火：同調三段時自燃倍率 +0.1／點'),
    ('fire', 0, 4, 'B0'): (IMPL, 'PERK ESSB_P_fire_0_4_B1 進入點 0x24（分頁 1 = 攻擊者）', '浴火：同調三段時帶火印記的攻擊者對你傷害 -30%；分頁 1 的語意需進遊戲確認，最壞情況是不生效'),
    ('fire', 0, 4, 'B1'): (IMPL, 'ESSBElem.OverheatCap + ESSBElem.FireHitMult', '熔爐：過熱上限 10 → 20，過熱中火附傷 +50% → +80%'),
    ('fire', 1, 0, 'M'): (IMPL, 'ESSBElem.OpenStacks', '開印熱度 +1／每 5 點'),
    ('fire', 1, 0, 'B0'): (IMPL, 'ESSBElem.OpenStacks', '引火：開印熱度 +2 → +5'),
    ('fire', 1, 1, 'M'): (IMPL, 'ESSBElem.FireHitMult（GetOpenBoost）', '開印後 5 秒內火附傷 +1%／點'),
    ('fire', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult → ESSBController.ApplyProc', '烈火點燃：開印那一擊附傷 ×1.5'),
    ('fire', 1, 1, 'B1'): (IMPL, 'ESSBElem.OpenFire', '餘熱：開印時回復 15 耐力'),
    ('fire', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus → ESSBController.ApplyMark', '火印記持續 +0.2 秒／點'),
    ('fire', 1, 2, 'B0'): (IMPL, 'ESSBElem.OpenFire', '焰起強化：開印額外對範圍內敵人一次火傷'),
    ('fire', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened → ESSBController.ForceOpenOn', '火臨：開形態時對 2 + 0.2×點 公尺內敵人各開印一次'),
    ('fire', 1, 3, 'B0'): (IMPL, 'ESSBElem.OpenFire', '烈火之始：開印時目標生命 >80% 則熱度直接 8'),
    ('fire', 1, 3, 'B1'): (IMPL, 'ESSBElem.HasTinder → ESSBStatus.Tick', '火種：熱度不因未命中歸零'),
    ('fire', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult → ESSBReactions.Open', '開印效果 +3%／點'),
    ('fire', 1, 4, 'B0'): (IMPL, 'ESSBElem.OpenFire → ESSBElem.Detonate', '先燃：同調三段時開印立即 ×0.5 爆燃'),
    ('fire', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('fire', 2, 0, 'B0'): (IMPL, 'ESSBElem.Detonate', '猛爆：爆燃不消耗熱度'),
    ('fire', 2, 0, 'B1'): (IMPL, 'ESSBElem.VentMult', '洩壓：融斷時每點過熱讓爆燃 +10%，熔身中以剩餘秒數 ×2 計'),
    ('fire', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '火印記的融斷 +2%／點'),
    ('fire', 2, 1, 'B0'): (IMPL, 'ESSBElem.Detonate', '熾焰：熱度 ≥8 時爆燃 ×1.5'),
    ('fire', 2, 1, 'B1'): (IMPL, 'ESSBElem.KeepHeatOnBurst → ESSBElem.EndFireNodes', '熔斷：融斷後目標熱度保留'),
    ('fire', 2, 2, 'M'): (IMPL, 'ESSBElem.DetonatePerLayer', '爆燃每層熱度倍率 +0.01／點（0.2 → 0.35）'),
    ('fire', 2, 2, 'B0'): (IMPL, 'ESSBElem.EndFireNodes → ESSBStatus.SetNextOpenMult', '餘燼：火終焉後接管元素的開印 ×1.5'),
    ('fire', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '火印記的融斷再 +2%／點'),
    ('fire', 2, 3, 'B0'): (IMPL, 'ESSBElem.EndFireNodes', '焚天：火終焉時 3 公尺內所有帶熱度目標一起爆燃'),
    ('fire', 2, 3, 'B1'): (IMPL, 'ESSBElem.Detonate', '火葬：爆燃擊殺的目標對附近敵人再爆 ×0.5（以套用後的生命 ≤0 判定，需進遊戲驗證時序）'),
    ('fire', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult', '爆燃 +3%／點'),
    ('fire', 2, 4, 'B0'): (IMPL, 'ESSBElem.EndFireNodes → ESSBController.StartDomain', '火域：融斷後 5 秒火域，內部敵人受火傷 +20%、熱度累積 ×2'),

    # ================= 5.4 冰霜（tree 1）
    ('frost', 0, 0, 'M'): (IMPL, 'ESSBElem.HitStacks', '每次命中凍結累積 +5%／點（小數以機率補足）'),
    ('frost', 0, 0, 'B0'): (IMPL, 'ESSBElem.HitStacks', '寒蝕：重擊凍結 +2'),
    ('frost', 0, 1, 'M'): (IMPL, 'ESSBElem.FrostHitMult', '冰附傷 +1%／點'),
    ('frost', 0, 1, 'B0'): (IMPL, 'ESSBElem.OnFrozenTick', '深寒：冰封中耐力不回復、攻擊 -20%（自有 MeleeDebuff）'),
    ('frost', 0, 1, 'B1'): (IMPL, 'PERK ESSB_P_frost_0_1_B2 進入點 0x24', '霜膚：冰形態受傷 -5%'),
    ('frost', 0, 2, 'M'): (IMPL, 'ESSBElem.FrostHitMult', '冰封目標受冰附傷 +2%／點'),
    ('frost', 0, 2, 'B0'): (IMPL, 'ESSBElem.FrozenExtraSeconds / FrozenResidual → ESSBStatus.Tick', '永凍：冰封 +2 秒、結束後凍結保留一半'),
    ('frost', 0, 2, 'B1'): (IMPL, 'ESSBElem.OnKill → ESSBController.Tick', '連鎖冰封：冰封目標死亡時附近凍結 +3、減速 30% 3 秒'),
    ('frost', 0, 3, 'M'): (IMPL, 'ESSBElem.FrostHitMult', '同調每段冰附傷 +1%／點'),
    ('frost', 0, 3, 'B0'): (IMPL, 'ESSBController.AddIceShield + PERK ESSB_P_frost_0_3_B1 進入點 0x24', '冰盾：層數由命中累積（上限 5），抵消 30% 傷害；round 2 的 ESSBGuard.OnHitEx 補上「被打消耗一層」'),
    ('frost', 0, 3, 'B1'): (IMPL, 'ESSBGuard.OnHitEx', '寒反：近戰攻擊你的敵人被減速 30% 3 秒，每攻擊者 3 秒一次'),
    ('frost', 0, 4, 'M'): (IMPL, 'ESSBElem.OnFrozenTick', '絕對零度：同調三段時冰封減速再 -2%／點（自有強減速，上限 90%，不排除首領）'),
    ('frost', 0, 4, 'B0'): (IMPL, 'ESSBElem.OnTick → ESSBController.TakeIceHeart', '冰心：生命 <30% 時每 30 秒自動冰封附近帶寒意的敵人'),
    ('frost', 1, 0, 'M'): (IMPL, 'ESSBElem.OpenStacks', '開印凍結 +1／每 3 點'),
    ('frost', 1, 0, 'B0'): (IMPL, 'ESSBElem.OpenFrost → ESSBController.AddStackTo', '寒潮：開印時附近 1 人凍結 +2'),
    ('frost', 1, 1, 'M'): (IMPL, 'ESSBElem.FrostHitMult（GetOpenBoost）', '開印後 5 秒內冰附傷 +1%／點'),
    ('frost', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '深霜結：開印那一擊附傷 ×1.5'),
    ('frost', 1, 1, 'B1'): (IMPL, 'ESSBElem.OpenFrost', '冰甲：開印時 +1 冰盾'),
    ('frost', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '冰印記持續 +0.2 秒／點'),
    ('frost', 1, 2, 'B0'): (IMPL, 'ESSBElem.OnFormOpened', '冰臨強化：冰臨附帶減速 30% 3 秒'),
    ('frost', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '冰臨：開形態時對 2 + 0.2×點 公尺內敵人各開印一次'),
    ('frost', 1, 3, 'B0'): (IMPL, 'ESSBElem.OpenFrost', '霜鎖：開印目標 3 秒內移速 -30%'),
    ('frost', 1, 3, 'B1'): (IMPL, 'ESSBElem.OpenFrost + PERK ESSB_P_frost_1_3_B2 進入點 0x24', '冰晶：開印時你受傷 -10% 3 秒（讀 ESSB_GuardIce）'),
    ('frost', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('frost', 1, 4, 'B0'): (IMPL, 'ESSBElem.OpenFrost', '絕霜：同調三段時開印直接冰封'),
    ('frost', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('frost', 2, 0, 'B0'): (IMPL, 'ESSBElem.ShatterThreshold', '銳碎：處決門檻 20% → 30%'),
    ('frost', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '冰印記的融斷 +2%／點'),
    ('frost', 2, 1, 'B0'): (IMPL, 'ESSBElem.ShatterArea', '冰崩：碎冰改為 3 公尺範圍，命中所有冰封目標'),
    ('frost', 2, 1, 'B1'): (IMPL, 'ESSBElem.FrostBurstShatter → ESSBReactions.EndFrost', '冰封融斷：融斷時冰封目標視同碎冰（碎冰本體本來就含處決判定）'),
    ('frost', 2, 2, 'M'): (IMPL, 'ESSBElem.OnEnd → ESSBController.SetEndBoost', '終焉後 5 秒內接管元素附傷 +1%／點'),
    ('frost', 2, 2, 'B0'): (IMPL, 'ESSBElem.EndFrostNodes → ESSBController.SetNextMarkBonus', '寒留：冰終焉後接管元素的印記持續 +4 秒'),
    ('frost', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '冰印記的融斷再 +2%／點'),
    ('frost', 2, 3, 'B0'): (IMPL, 'ESSBElem.EndFrostNodes → ShatterArea', '冰河：冰終焉時目標若冰封，範圍內冰封目標一起碎冰、各自判定處決'),
    ('frost', 2, 3, 'B1'): (IMPL, 'ESSBElem.Shatter', '碎甲加深：碎冰的碎甲 10% → 20%'),
    ('frost', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult', '碎冰 +3%／點'),
    ('frost', 2, 4, 'B0'): (IMPL, 'ESSBElem.Shatter', '冰棺：碎冰未處決的目標再冰封'),
    ('frost', 2, 4, 'B1'): (IMPL, 'ESSBElem.EndFrostNodes → ESSBController.StartDomain/TickDomain', '冰原：融斷後 5 秒冰原，內部敵人減速 50%、凍結累積 ×2，玩家在其中免疫減速'),

    # ================= 5.5 雷電（tree 2）
    ('lightning', 0, 0, 'M'): (IMPL, 'ESSBElem.Discharge', '放電每格電荷傷害 +1%／點'),
    ('lightning', 0, 0, 'B0'): (IMPL, 'SPEL ESSB_Ability_Induction + ESSBController.RefreshAbilities', '感應：雷形態時掛 MagickaRateMult +20 的自有能力'),
    ('lightning', 0, 1, 'M'): (IMPL, 'ESSBElem.ShockHitMult', '雷附傷 +1%／點'),
    ('lightning', 0, 1, 'B0'): (IMPL, 'ESSBElem.Discharge', '電弧：放電跳躍傷害 40% → 80%（規劃 2.6 的基礎放電已含 2 人跳躍，分支解讀為加成）'),
    ('lightning', 0, 1, 'B1'): (IMPL, 'ESSBGuard.OnHitEx', '靜電：被近戰命中時攻擊者感電（你 +1 電荷、他 -B_max 魔力），每攻擊者 3 秒一次'),
    ('lightning', 0, 2, 'M'): (IMPL, 'ESSBElem.ChargeCap → ESSBController.AddSelf', '電荷上限 +1／每 3 點'),
    ('lightning', 0, 2, 'B0'): (IMPL, 'ESSBElem.StormChance → ESSBController.OnWeaponHit', '雷暴：電荷滿時普攻 30% 機率放電'),
    ('lightning', 0, 3, 'M'): (IMPL, 'ESSBElem.ShockHitMult', '同調每段雷附傷 +1%／點'),
    ('lightning', 0, 3, 'B0'): (IMPL, 'PERK ESSB_P_lightning_0_3_B1 進入點 0x24', '電盾：電荷 ≥5 時受傷 -15%'),
    ('lightning', 0, 3, 'B1'): (IMPL, 'ESSBElem.Discharge + PERK ESSB_P_lightning_0_3_B2 進入點 0x24', '疾電：放電後 3 秒受傷 -15%（讀 ESSB_ShockRecent）'),
    ('lightning', 0, 4, 'M'): (IMPL, 'ESSBElem.DischargeAll', '天雷：同調三段時放電改為對 2 + 0.2×點 公尺內所有感電目標'),
    ('lightning', 0, 4, 'B0'): (IMPL, 'ESSBElem.OnTick', '雷神：同調三段電荷滿時自動放電並回魔'),
    ('lightning', 1, 0, 'M'): (IMPL, 'ESSBElem.OpenStacks', '開印電荷 +1／每 5 點'),
    ('lightning', 1, 0, 'B0'): (IMPL, 'ESSBElem.OpenShock', '傳導：開印時附近 1 人也感電（補一個雷印記）'),
    ('lightning', 1, 1, 'M'): (IMPL, 'ESSBElem.ShockHitMult（GetOpenBoost）', '開印後 5 秒內雷附傷 +1%／點'),
    ('lightning', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '強感電：開印那一擊附傷 ×1.5'),
    ('lightning', 1, 1, 'B1'): (IMPL, 'ESSBElem.OpenShock', '充能開印：開印時回復 B_max 魔力'),
    ('lightning', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '雷印記持續 +0.2 秒／點'),
    ('lightning', 1, 2, 'B0'): (IMPL, 'ESSBElem.OnFormOpened', '雷臨強化：雷臨時立即 +5 電荷'),
    ('lightning', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '雷臨：開形態時對 2 + 0.2×點 公尺內敵人各開印一次'),
    ('lightning', 1, 3, 'B0'): (IMPL, 'ESSBElem.OpenShock（自有 MagicResistDebuff）', '感電削弱：感電目標魔抗 -10%'),
    ('lightning', 1, 3, 'B1'): (IMPL, 'ESSBElem.OpenShock（自有 Haste）', '雷閃：開印後 2 秒移速 +15%'),
    ('lightning', 1, 3, 'B2'): (IMPL, 'ESSBElem.Discharge + ESSBElem.ShockHitMult', '電蝕：削魔比例 50% → 100%，目標魔力為 0 時雷附傷 +25%'),
    ('lightning', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('lightning', 1, 4, 'B0'): (IMPL, 'ESSBElem.OpenShock', '先雷：同調三段時開印立即放電一次，不消耗電荷'),
    ('lightning', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('lightning', 2, 0, 'B0'): (IMPL, 'ESSBElem.Discharge', '連鎖：放電跳躍 2 → 5 人'),
    ('lightning', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '雷印記的融斷 +2%／點'),
    ('lightning', 2, 1, 'B0'): (IMPL, 'ESSBElem.Discharge', '蓄餘：雷終焉不消耗電荷'),
    ('lightning', 2, 1, 'B1'): (IMPL, 'ESSBElem.ShockBurstBonus', '雷斷：雷印記融斷時附加全部電荷的放電加成（×(1+0.3×電荷)）'),
    ('lightning', 2, 2, 'M'): (IMPL, 'ESSBElem.OnEnd → ESSBController.SetEndBoost', '終焉後 5 秒內接管元素附傷 +1%／點'),
    ('lightning', 2, 2, 'B0'): (IMPL, 'ESSBElem.EndShockNodes → ESSBController.SetPendingDischarge/AfterOpen', '餘電：雷終焉後接管元素的開印附帶 ×0.5 放電'),
    ('lightning', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '雷印記的融斷再 +2%／點'),
    ('lightning', 2, 3, 'B0'): (IMPL, 'ESSBElem.EndShockNodes', '雷殛：雷終焉對範圍內所有感電目標各一次全額放電'),
    ('lightning', 2, 3, 'B1'): (IMPL, 'ESSBElem.OverloadMult', '過載終焉：終焉時電荷 ≥8 則傷害 ×2'),
    ('lightning', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult', '放電 +3%／點'),
    ('lightning', 2, 4, 'B0'): (IMPL, 'ESSBElem.EndShockNodes → ESSBController.OnWeaponHit', '雷霆：雷印記融斷後 5 秒內每次命中都放電 ×0.3'),

    # ================= 5.6 大地（tree 3）
    ('earth', 0, 0, 'M'): (IMPL, 'ESSBElem2.FissureArmor → ESSBReactions.Open(4)', '裂痕護甲削減 -30 → -60（+2／點），走自有 ESSB_Util_ArmorDebuff'),
    ('earth', 0, 0, 'B0'): (IMPL, 'ESSBElem2.RockArmorPerLayer → ESSBController.SyncRockArmor', '磐石：岩甲每層護甲 15 → 25（自有 ESSB_Util_ArmorBuff，AV 39 原型 34，層數變動時重下）'),
    ('earth', 0, 1, 'M'): (IMPL, 'ESSBElem2.EarthHitMult', '土附傷 +1%／點'),
    ('earth', 0, 1, 'B0'): (IMPL, 'ESSBElem2.OnEarthHit', '震擊：重擊消耗滿層裂痕，×1.5 爆傷並削 50 耐力'),
    ('earth', 0, 1, 'B1'): (IMPL, 'ESSBElem2.RockCap → ESSBController.AddSelf(2)', '厚土：岩甲上限 5 → 10'),
    ('earth', 0, 2, 'M'): (IMPL, 'ESSBElem2.OnEarthHit', '命中削減目標耐力 +0.5／點'),
    ('earth', 0, 2, 'B0'): (IMPL, 'ESSBElem2.OnEarthHit', '汲力：命中削減的耐力一半轉為你的耐力'),
    ('earth', 0, 3, 'M'): (IMPL, 'ESSBElem2.EarthHitMult', '同調每段土附傷 +1%／點'),
    ('earth', 0, 3, 'B0'): (IMPL, 'PERK ESSB_P_earth_0_3_B1 進入點 0x21（受到的擊退幅度）', '不動：岩甲 ≥5 時 ×0 ＝ 免疫擊退；0x21 由原版 TowerOfStrength（0.5）與 MQGreybeardsFus（0.75）實測'),
    ('earth', 0, 3, 'B1'): (IMPL, 'ESSBElem2.OnEarthRetaliate ← ESSBGuard.OnHitEx', '反震：岩甲滿層被近戰命中反震 B_max ×2.0 土傷並使攻擊者跌倒，10 秒一次，清空岩甲'),
    ('earth', 0, 4, 'M'): (IMPL, 'ESSBElem2.OnEarthHit → ESSBController.Knockdown', '地動：同調三段重擊對耐力 <30% 的目標跌倒，機率 5%／點'),
    ('earth', 0, 4, 'B0'): (IMPL, 'ESSBGuard.OnHitEx + PERK ESSB_P_earth_0_4_B1 進入點 0x24 ×5 段', '山岳：同調三段岩甲不因被打減少；物理減傷每層 +1%（基礎在 ESSB_P_BaseRules）→ +3%'),
    ('earth', 1, 0, 'M'): (IMPL, 'ESSBElem2.OpenStacks(4)', '開印岩甲 +1／每 5 點'),
    ('earth', 1, 0, 'B0'): (IMPL, 'ESSBElem2.OpenEarth', '震波：開印時附近 1 人也裂痕'),
    ('earth', 1, 1, 'M'): (IMPL, 'ESSBElem2.EarthHitMult（GetOpenBoost(4)）', '開印後 5 秒內土附傷 +1%／點'),
    ('earth', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult → ESSBController.ApplyProc', '深裂痕：開印那一擊附傷 ×1.5'),
    ('earth', 1, 1, 'B1'): (IMPL, 'ESSBElem2.OpenStacks(4)', '岩膚：開印岩甲 +2 → +4'),
    ('earth', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus → ESSBController.ApplyMark', '土印記持續 +0.2 秒／點'),
    ('earth', 1, 2, 'B0'): (IMPL, 'ESSBElem2.OnFormOpened(4)', '地臨強化：地臨時岩甲滿層，範圍內敵人減速 30% 3 秒'),
    ('earth', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened → ESSBController.ForceOpenOn', '地臨：開土形態時對範圍內敵人各開印一次，2 公尺 +0.2 公尺／點'),
    ('earth', 1, 3, 'B0'): (IMPL, 'ESSBElem2.OpenEarth', '地基：開印目標 3 秒內移速 -30%'),
    ('earth', 1, 3, 'B1'): (IMPL, 'ESSBElem2.OpenEarth → ESSBController.StartDomain(4, 3)', '裂地：開印在目標腳下留 3 秒減速地帶（共用單一領域格）'),
    ('earth', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('earth', 1, 4, 'B0'): (IMPL, 'ESSBElem2.OpenEarth → Quake(0.5, abKnock = False)', '先震：同調三段開印立即一次 ×0.5 地震，不含跌倒'),
    ('earth', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('earth', 2, 0, 'B0'): (IMPL, 'ESSBElem2.QuakeK', '崩裂：地震 ×1.5 → ×2.0'),
    ('earth', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '土印記的融斷 +2%／點'),
    ('earth', 2, 1, 'B0'): (IMPL, 'ESSBElem2.QuakeRadius', '廣震：地震範圍 210 → 350 單位（3 → 5 公尺）'),
    ('earth', 2, 1, 'B1'): (IMPL, 'ESSBElem2.EndEarthNodes → ESSBController.SetSelf(2)', '固土：土終焉後你岩甲滿層'),
    ('earth', 2, 2, 'M'): (IMPL, 'ESSBElem2.QuakeStamina', '地震耐力削減 +3%／點'),
    ('earth', 2, 2, 'B0'): (IMPL, 'ESSBElem2.EndEarthNodes → StartDomain(4, 3)', '地斷：土印記融斷附帶 3 秒泥沼，內部減速 40%'),
    ('earth', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '土印記的融斷再 +2%／點'),
    ('earth', 2, 3, 'B0'): (IMPL, 'ESSBElem2.EndEarthNodes', '山崩：土終焉對範圍內所有帶裂痕的目標各一次地震'),
    ('earth', 2, 3, 'B1'): (IMPL, 'ESSBElem2.QuakeOne', '塵暴：地震使範圍內敵人攻擊 -20% 3 秒'),
    ('earth', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult → ESSBElem2.Quake', '地震 +3%／點'),
    ('earth', 2, 4, 'B0'): (IMPL, 'ESSBElem2.EndEarthNodes → ESSBController.TickDomain', '地裂：融斷後 5 秒地裂帶，內部敵人減速 50%、耐力不回復（ESSB_Util_StaminaRateDebuff -100）'),

    # ================= 5.7 風（tree 4）
    ('wind', 0, 0, 'M'): (IMPL, 'ESSBElem2.WindBladeMult', '風刃傷害 +2%／點'),
    ('wind', 0, 0, 'B0'): (IMPL, 'ESSBElem2.WindBlade', '迴旋：風刃改為對附近 2 人各一段'),
    ('wind', 0, 1, 'M'): (IMPL, 'ESSBElem2.WindHitMult', '風附傷 +1%／點'),
    ('wind', 0, 1, 'B0'): (IMPL, 'ESSBElem2.WindThreshold', '亂舞：風勢門檻 4 → 3'),
    ('wind', 0, 1, 'B1'): (IMPL, 'ESSBElem2.OnWindHit', '順風：命中回復耐力 5'),
    ('wind', 0, 2, 'M'): (IMPL, 'ESSBElem2.WindSpeedBonus → ESSBController.RefreshWindAbilities', '風形態移速 +10% → +17.5%；SPEL ESSB_Ability_WindSpeed，AddSpell 前 SetNthEffectMagnitude'),
    ('wind', 0, 2, 'B0'): (IMPL, 'ESSBElem2.WindBladeOne', '追風：風刃命中回耐力 3 並讓目標失衡'),
    ('wind', 0, 2, 'B1'): (IMPL, 'SPEL ESSB_SilentAbility + ESSBController.RefreshWindStealth', '無聲：Muffle 1.0 + 潛行移速 +20%；潛行狀態在既有的每秒 tick 讀一次，不開每幀迴圈'),
    ('wind', 0, 3, 'M'): (IMPL, 'ESSBElem2.WindHitMult', '同調每段風附傷 +1%／點'),
    ('wind', 0, 3, 'B0'): (IMPL, 'ESSBGuard.OnHitEx + PERK ESSB_P_wind_0_3_B1 進入點 0x24 ×0', '殘影：風勢滿被近戰命中擲 30%，成功就消耗風勢並開 2 秒受傷 ×0 視窗，抵掉一次後立刻關閉'),
    ('wind', 0, 3, 'B1'): (IMPL, 'ESSBElem2.WindSpeedBonus', '疾風：移速再 +10%。「衝刺耐力消耗 -50%」未實作：本機 Skyrim.esm 沒有任何衝刺耐力的進入點用例可比對索引'),
    ('wind', 0, 3, 'B2'): (IMPL, 'ESSBElem2.SneakMult / WindBladeMult', '暗風：潛行風附傷 ×3 → ×5，潛行送出的風刃 ×2'),
    ('wind', 0, 4, 'M'): (IMPL, 'ESSBElem2.OnWindHit', '千刃：同調三段時每次命中 5%／點機率附帶風刃'),
    ('wind', 0, 4, 'B0'): (IMPL, 'ESSBElem2.WindSlowImmune → ESSBNodes.SelfSlowImmune；ESSBElem2.TargetDamageMult', '御風：同調三段免疫自有減速；失衡目標受你所有傷害 +30%'),
    ('wind', 1, 0, 'M'): (IMPL, 'ESSBElem2.OpenStacks(5)', '開印風勢 +1／每 5 點'),
    ('wind', 1, 0, 'B0'): (IMPL, 'ESSBElem2.OpenWind', '風襲：開印時附近 1 人也風痕'),
    ('wind', 1, 1, 'M'): (IMPL, 'ESSBElem2.PullDistance → ESSBController.PullIn', '開印拉近 1.5 → 3 公尺（+0.1／點）；ApplyHavokImpulse，每目標 3 秒一次'),
    ('wind', 1, 1, 'B0'): (IMPL, 'ESSBElem2.OpenStacks(5)', '疾風痕：開印風勢直接滿'),
    ('wind', 1, 1, 'B1'): (IMPL, 'ESSBElem2.OpenWind', '輕躍：開印後 3 秒移速 +10%'),
    ('wind', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '風印記持續 +0.2 秒／點'),
    ('wind', 1, 2, 'B0'): (IMPL, 'ESSBElem2.OnFormOpened(5) → ESSBController.PullIn', '氣旋：風臨時把範圍內敵人拉到你面前 2 公尺'),
    ('wind', 1, 2, 'B1'): (IMPL, 'ESSBElem2.OpenWind（ESSBController.LastHitWasSneak）', '奇襲：潛行攻擊的開印同時觸發終焉（abChain 防遞迴），且不拉近'),
    ('wind', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '風臨：開風形態時對範圍內敵人各開印一次'),
    ('wind', 1, 3, 'B0'): (IMPL, 'ESSBController.PullTo', '牽引：拉近的目標 2 秒內自有減速 80%'),
    ('wind', 1, 3, 'B1'): (IMPL, 'ESSBElem2.OpenWind', '氣流：開印時回復 10 耐力'),
    ('wind', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('wind', 1, 4, 'B0'): (IMPL, 'ESSBElem2.OpenWind', '先風：同調三段時開印附帶一段風刃'),
    ('wind', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('wind', 2, 0, 'B0'): (IMPL, 'ESSBReactions.EndWind', '亂流：風刃附近目標 2 → 5 人'),
    ('wind', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '風印記的融斷 +2%／點'),
    ('wind', 2, 1, 'B0'): (IMPL, 'ESSBElem2.BlowAway → ESSBController.LiftUp → ESSBStatus 浮空', '上天：吹飛改吹上天；浮空是自有的 2 秒狀態（不讀物理），落地傷害在到期時結算'),
    ('wind', 2, 1, 'B1'): (IMPL, 'ESSBElem2.EndWindNodes', '風斷：風印記融斷時每個目標各兩段風刃'),
    ('wind', 2, 2, 'M'): (IMPL, 'ESSBElem2.BlowDistance', '吹飛距離 3 → 6 公尺（+0.2／點）'),
    ('wind', 2, 2, 'B0'): (IMPL, 'ESSBElem2.EndWindNodes → ESSBController.PullTo', '風渦：終焉時 5 公尺內敵人被拉向目標聚攏'),
    ('wind', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '風印記的融斷再 +2%／點'),
    ('wind', 2, 3, 'B0'): (IMPL, 'ESSBElem2.EndWindNodes', '颶風：融斷的吹上天改為對範圍內所有敵人，不限帶風印記'),
    ('wind', 2, 3, 'B1'): (IMPL, 'ESSBController.SetWindFollow → OnWeaponHit', '順勢：風終焉後 5 秒內接管元素的命中皆附帶一段風刃'),
    ('wind', 2, 4, 'M'): (IMPL, 'ESSBElem2.LandingDamage', '落地傷害 ×0.5 → ×1.25（+5%／點）'),
    ('wind', 2, 4, 'B0'): (IMPL, 'ESSBElem2.TargetDamageMult / WindBladeOne', '空中追擊：浮空目標受你所有「本模組」傷害 ×1.5；引擎武器傷害無法以目標狀態為條件（0x23 的條件分頁 1 是武器，見實作紀錄），風刃命中空中目標再推高 1 公尺'),
    ('wind', 2, 4, 'B1'): (IMPL, 'ESSBElem2.OnKill → ESSBController.KeepSneak / TakeKillStreak', '連殺：潛行擊殺後 5 秒 PO3 PreventActorDetection，下一次潛行附傷 ×2 並重置奇襲'),

    # ================= 5.8 鮮血（tree 5）
    ('blood', 0, 0, 'M'): (IMPL, 'ESSBElem2.BleedTickMult / BleedDrainPercent → ESSBStatus.Tick', '流血每層傷害 +2%／點，放血係數 0.3% → 0.45%（首領同比例，0.1% → 0.15%）'),
    ('blood', 0, 0, 'B0'): (IMPL, 'ESSBController.BloodCostScale', '血氣：維持扣血與重擊扣血減半'),
    ('blood', 0, 0, 'B1'): (IMPL, 'ESSBElem2.BleedCap → ESSBController.StackCap(5)', '深創：血痕上限 8 → 12'),
    ('blood', 0, 1, 'M'): (IMPL, 'ESSBElem2.BloodHitMult', '血附傷 +1%／點'),
    ('blood', 0, 1, 'B0'): (IMPL, 'ESSBElem2.OnKill ← ESSBGuard.OnActorKilled + PERK ESSB_P_blood_0_1_B1 進入點 0x23', '飲血：擊殺流血目標回血 20%，10 秒嗜血＝命中效果 +20%、吸血 +10%、武器傷害 +10%，不受血位影響'),
    ('blood', 0, 1, 'B1'): (IMPL, 'ESSBController.Leech（ESSB_Util_TempHealth）', '血盾：吸血溢出轉 20 秒臨時生命上限，上限 20% 生命'),
    ('blood', 0, 2, 'M'): (IMPL, 'ESSBController.GetBloodLeechRatio', '吸血比例各血位 +1%／點'),
    ('blood', 0, 2, 'B0'): (IMPL, 'ESSBController.BloodPercent', '逆流：查表百分比反轉（命中與吸血兩條曲線），損血曲線走 BloodDrainCurve 不反轉'),
    ('blood', 0, 2, 'B1'): (IMPL, 'ESSBController.ApplyInherit（SPEL ESSB_InheritSpell，7 個 Peak Value Modifier）', '血承：擊殺流血目標吸收其火冰電毒魔抗各 50%、護甲 20%、最大生命 10%，15 秒，重掛即取代'),
    ('blood', 0, 3, 'M'): (IMPL, 'ESSBElem2.BloodHitMult', '同調每段血附傷 +1%／點'),
    ('blood', 0, 3, 'B0'): (IMPL, 'ESSBElem2.BleedTickMult', '止血：低血位（<30%）時流血傷害 ×1.5'),
    ('blood', 0, 3, 'B1'): (IMPL, 'ESSBController.GetBloodHitMult / GetBloodLeechRatio', '血怒：中血位（30–70%）命中效果 +15%、吸血 +15%'),
    ('blood', 0, 4, 'M'): (IMPL, 'ESSBElem2.SurgeRadius → ESSBReactions.EndBlood', '血海：同調三段時血潮改為範圍 1 公尺 +0.2 公尺／點'),
    ('blood', 0, 4, 'B0'): (IMPL, 'ESSBController.BloodCostScale / ESSBElem2.OnKill', '不死：同調三段維持扣血歸零；流血目標死亡回滿耐力'),
    ('blood', 1, 0, 'M'): (IMPL, 'ESSBElem2.OpenStacks(6)', '開印流血 +1 層／每 5 點'),
    ('blood', 1, 0, 'B0'): (IMPL, 'ESSBElem2.OpenBlood', '血濺：開印時附近 1 人流血 1 層'),
    ('blood', 1, 1, 'M'): (IMPL, 'ESSBElem2.BloodHitMult', '開印後 5 秒內血附傷 +1%／點'),
    ('blood', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '深血痕：開印那一擊附傷 ×1.5'),
    ('blood', 1, 1, 'B1'): (IMPL, 'ESSBElem2.OpenBlood', '開印回血：開印回血 B_max ×0.5，低血位 ×2'),
    ('blood', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '血印記持續 +0.2 秒／點'),
    ('blood', 1, 2, 'B0'): (IMPL, 'ESSBElem2.OnFormOpened(6) → ESSBController.SetNoBloodCost(10)', '血臨強化：血臨後 10 秒不扣血'),
    ('blood', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '血臨：開血形態時對範圍內敵人各開印一次'),
    ('blood', 1, 3, 'B0'): (IMPL, 'ESSBElem2.OpenBlood（ESSB_Util_HealRateDebuff）', '血咒：開印目標 5 秒受治療 -50%；原版沒有「受治療」修正，改以 HealRateMult -50 表達，見實作紀錄'),
    ('blood', 1, 3, 'B1'): (IMPL, 'ESSBElem2.OpenBlood', '血脈：開印時 +2 同調'),
    ('blood', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('blood', 1, 4, 'B0'): (IMPL, 'ESSBElem2.OpenBlood', '血祭之始：同調三段時開印立即結算一次 ×0.5 血潮'),
    ('blood', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('blood', 2, 0, 'B0'): (IMPL, 'ESSBReactions.EndBlood', '飽飲：血潮結算的流血傷害 ×1.5'),
    ('blood', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '血印記的融斷 +2%／點'),
    ('blood', 2, 1, 'B0'): (IMPL, 'ESSBElem2.EndBloodNodes', '血漫：血潮結算時附近流血目標一起血潮（abChain 防遞迴）'),
    ('blood', 2, 1, 'B1'): (IMPL, 'ESSBReactions.EndBlood → ESSBController.Leech', '血斷：血印記融斷治療你該傷害的 50%'),
    ('blood', 2, 2, 'M'): (IMPL, 'ESSBElem2.SurgeHealMult', '血潮治療倍率 ×2，每點 +0.1'),
    ('blood', 2, 2, 'B0'): (IMPL, 'ESSBElem2.EndBloodNodes → ESSBController.SetNoBloodCost(8)', '血約：血終焉後 8 秒不扣血'),
    ('blood', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '血印記的融斷再 +2%／點'),
    ('blood', 2, 3, 'B0'): (IMPL, 'ESSBReactions.EndBlood → ESSBController.PayBloodCost', '血契：高血位（≥70%）時血終焉損失 10% 生命，血潮 ×2'),
    ('blood', 2, 3, 'B1'): (IMPL, 'ESSBElem2.SurgePercent', '放血終焉：血潮的當前生命項 10% → 20%（首領 3% → 6%）'),
    ('blood', 2, 3, 'B2'): (IMPL, 'ESSBElem2.EndBloodNodes → ESSBController.SetPendingBleed(2)', '血引：血終焉後接管元素的開印附帶流血 2 層'),
    ('blood', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult → ESSBReactions.EndBlood', '血潮 +3%／點'),
    ('blood', 2, 4, 'B0'): (IMPL, 'ESSBElem2.EndBloodNodes → StartDomain(6) → ESSBController.TickDomain', '血池：血印記融斷後留下 5 秒血池，你在其中每秒回血 B_max'),

    # ================= 5.9 神聖（tree 6）
    ('divine', 0, 0, 'M'): (IMPL, 'ESSBElem2.HolyVulnerability', '聖印每層目標受聖傷 +1%／點（含規劃 2.6 的基礎 +20%），附傷與裁決共用同一個函式'),
    ('divine', 0, 0, 'B0'): (IMPL, 'ESSBElem2.OnDivineHit', '護持：命中獲得 10% 魔抗 3 秒'),
    ('divine', 0, 0, 'B1'): (IMPL, 'ESSBElem2.DivineHitMult → ESSBController.IsNecromancer', '驅魔：對死靈施法者傷害 +50%；判定＝職業 CombatMageNecro ∪ 陣營 NecromancerFaction ∪ 身邊有復生僕從'),
    ('divine', 0, 1, 'M'): (IMPL, 'ESSBElem2.DivineHitMult', '聖附傷 +1%／點'),
    ('divine', 0, 1, 'B0'): (IMPL, 'ESSBElem2.OnDivineHit', '神罰：聖印滿層時每次命中額外一次 50% 聖光'),
    ('divine', 0, 1, 'B1'): (IMPL, 'ESSBElem2.OnDivineHit + PERK ESSB_P_divine_0_1_B2 進入點 0x29 ×5 段', '聖盾：每命中 +1 層（最多 5），每層受到的法術強度 ×0.9；0x29 由原版 ElementalProtection 實測'),
    ('divine', 0, 2, 'M'): (IMPL, 'ESSBElem2.OnDivineHit', '命中回血 +2%／點（以 B_max 為基準）'),
    ('divine', 0, 2, 'B0'): (IMPL, 'ESSBElem2.EndDivineNodes', '光耀：裁決後附近亡靈魔族減速 40% 4 秒'),
    ('divine', 0, 2, 'B1'): (IMPL, 'ESSBElem2.OnAsh', '聖灰：敵人化為灰燼時你回復魔力 B_max ×2'),
    ('divine', 0, 3, 'M'): (IMPL, 'ESSBElem2.DivineHitMult', '同調每段聖附傷 +1%／點'),
    ('divine', 0, 3, 'B0'): (IMPL, 'ESSBElem2.HealAllies → ESSBController.ScanAllies', '祝福：命中時 6 公尺內同伴回血 B_max（ScanTargets 排除同伴，另走 ScanAllies）'),
    ('divine', 0, 3, 'B1'): (IMPL, 'ESSBElem2.OnTick → ESSBController.TakeSanctuary', '庇護：生命低於 30% 時自動聖盾滿層，每 30 秒一次'),
    ('divine', 0, 4, 'M'): (IMPL, 'ESSBElem2.JudgeArea', '天啟：同調三段時裁決改為範圍 1 公尺 +0.2 公尺／點'),
    ('divine', 0, 4, 'B0'): (IMPL, 'ESSBGuard.OnHitEx → TakeDivineSave + PERK ESSB_P_divine_0_4_B1 進入點 0x24 ×0', '神佑：生命降到 ≤1 時補回 1 點並給 2 秒受傷 ×0，脫戰重置。「清除所有負面」改為無敵視窗（DispelAllSpells 會連自己的增益一起洗掉，違反規劃 8 的洗淨守則）'),
    ('divine', 0, 4, 'B1'): (IMPL, 'ESSBElem2.ShouldAsh', '淨土：同調三段時神聖形態的所有擊殺都化灰，不限致命一擊是否神聖'),
    ('divine', 1, 0, 'M'): (IMPL, 'ESSBElem2.OpenDivine', '開印回血 +5%／點'),
    ('divine', 1, 0, 'B0'): (IMPL, 'ESSBElem2.OpenDivine', '聖輝：開印時附近 1 人也聖印'),
    ('divine', 1, 1, 'M'): (IMPL, 'ESSBElem2.DivineHitMult', '開印後 5 秒內聖附傷 +1%／點'),
    ('divine', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '慈光：開印那一擊附傷 ×1.5'),
    ('divine', 1, 1, 'B1'): (IMPL, 'ESSBElem2.OpenDivine', '聖護：開印時獲得 10% 魔抗 3 秒'),
    ('divine', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '聖印記持續 +0.2 秒／點'),
    ('divine', 1, 2, 'B0'): (IMPL, 'ESSBElem2.OnFormOpened(7)', '聖臨強化：聖臨時你與附近同伴回血 B_max ×2'),
    ('divine', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '聖臨：開聖形態時對範圍內敵人各開印一次'),
    ('divine', 1, 3, 'B0'): (IMPL, 'ESSBElem2.IsHolyPrey / HolyVulnerability', '聖痕：帶本模組聖印記的目標也吃亡靈魔族判定（裁決 ×3），非亡靈另 +10% 聖傷'),
    ('divine', 1, 3, 'B1'): (IMPL, 'ESSBElem2.OpenDivine → HealAllies', '聖光：開印時附近同伴回血 B_max'),
    ('divine', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('divine', 1, 4, 'B0'): (IMPL, 'ESSBElem2.OpenDivine → Judge(0.5)', '聖啟：同調三段時開印對亡靈魔族立即一次 ×0.5 裁決'),
    ('divine', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('divine', 2, 0, 'B0'): (IMPL, 'ESSBElem2.JudgeK', '重裁：裁決 ×2.0 → ×3.0'),
    ('divine', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '聖印記的融斷 +2%／點'),
    ('divine', 2, 1, 'B0'): (IMPL, 'ESSBElem2.JudgeArea', '廣裁：裁決改為 3 公尺範圍'),
    ('divine', 2, 1, 'B1'): (IMPL, 'ESSBElem2.EndDivineNodes', '聖斷：聖印記融斷每個目標治療你 B_max ×1.0'),
    ('divine', 2, 2, 'M'): (IMPL, 'ESSBElem.OnEnd → ESSBController.SetEndBoost / GetHitMult', '終焉後 5 秒內接管元素附傷 +1%／點（本輪順手把 round 1 只寫入沒讀取的那一半補上）'),
    ('divine', 2, 2, 'B0'): (IMPL, 'ESSBElem2.EndDivineNodes → StartDomain(7, 5) + PERK ESSB_P_divine_2_2_B1 進入點 0x24', '聖域：聖終焉後 5 秒，你在其中受傷 -20% 並每秒回血回魔'),
    ('divine', 2, 2, 'B1'): (IMPL, 'ESSBElem2.OnAsh', '淨灰：化灰時爆出聖光，附近亡靈受 B_max ×1.0 聖傷'),
    ('divine', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '聖印記的融斷再 +2%／點'),
    ('divine', 2, 3, 'B0'): (IMPL, 'ESSBElem2.EndDivineNodes → ESSBController.Execute', '處決：裁決處決範圍內低於 20% 生命的亡靈魔族；首領與必要角色改走 B_max ×5.0'),
    ('divine', 2, 3, 'B1'): (IMPL, 'ESSBElem2.EndDivineNodes → ESSBController.SetPendingHeal', '聖引：聖終焉後接管元素的開印治療你 B_max'),
    ('divine', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult → ESSBElem2.Judge', '裁決 +3%／點'),
    ('divine', 2, 4, 'B0'): (IMPL, 'ESSBElem2.EndDivineNodes → StartDomain(7, 8) + PERK ESSB_P_divine_2_4_B1 進入點 0x24', '神聖領域：聖印記融斷後留下 8 秒聖域'),

    # ================= 5.10 毒素（tree 7）
    ('poison', 0, 0, 'M'): (IMPL, 'ESSBElem3.PoisonTickMult → ESSBStatus.Tick', '毒層每層每秒傷害 +2%／點'),
    ('poison', 0, 0, 'B0'): (IMPL, 'SPEL ESSB_Ability_PoisonResist + ESSBController.RefreshAbilities', '免疫：毒形態掛上毒抗 +50%（AV 40）的自有常駐能力，關形態即移除'),
    ('poison', 0, 1, 'M'): (IMPL, 'ESSBElem3.PoisonHitMult', '毒附傷 +1%／點'),
    ('poison', 0, 1, 'B0'): (IMPL, 'ESSBElem3.OnPoisonHit', '衰弱：毒層 ≥5 時目標攻擊 -15% 3 秒（AV 34，同攻擊削弱）'),
    ('poison', 0, 1, 'B1'): (IMPL, 'ESSBGuard.OnHitEx → ESSBElem3.OnPoisonSkin', '毒皮：被近戰命中時攻擊者 +2 毒層，每攻擊者 3 秒一次'),
    ('poison', 0, 2, 'M'): (IMPL, 'ESSBElem3.SpreadInterval / SpreadTargets → ESSBStatus.Tick', '基礎擴散間隔 2 秒 → 10 點後 1 秒；點滿（15 點）的「0.5 秒」以「每秒傳兩個目標」表達，因為狀態容器是整數秒 tick'),
    ('poison', 0, 2, 'B0'): (IMPL, 'ESSBElem3.OnPoisonHit', '侵蝕：毒層 ≥10 時目標毒抗 -20% 6 秒'),
    ('poison', 0, 2, 'B1'): (IMPL, 'ESSBElem3.SpreadThreshold', '傳染門檻：基礎擴散門檻 5 層 → 1 層'),
    ('poison', 0, 3, 'M'): (IMPL, 'ESSBElem3.PoisonHitMult', '同調每段毒附傷 +1%／點'),
    ('poison', 0, 3, 'B0'): (IMPL, 'ESSBElem3.OnKill', '蔓延：中毒目標死亡時毒層以原層數傳給附近 5 人'),
    ('poison', 0, 3, 'B1'): (IMPL, 'ESSBElem3.PoisonFormTick → ESSBController.IsPoisoned', '以毒攻毒：你身上帶 MagicAlchHarmful 效果時 HealRateMult +20%'),
    ('poison', 0, 4, 'M'): (IMPL, 'ESSBElem3.PoisonTickHook ← ESSBStatus.Tick', '瘟疫：同調三段時每秒以 5%／點 的機率額外自動擴散一層'),
    ('poison', 0, 4, 'B0'): (IMPL, 'ESSBElem3.PoisonFormTick', '百毒不侵：同調三段時毒抗與疾病抗各 +100%（AV 40／45），附近中毒敵人每秒替你回血'),
    ('poison', 1, 0, 'M'): (IMPL, 'ESSBElem3.OpenStacks → ESSBReactions.Open', '開印毒層 3 +1／每 3 點'),
    ('poison', 1, 0, 'B0'): (IMPL, 'ESSBElem3.OpenPoison', '毒濺：開印時附近 1 人 +2 毒層'),
    ('poison', 1, 1, 'M'): (IMPL, 'ESSBElem3.PoisonHitMult（GetOpenBoost）', '開印後 5 秒內毒附傷 +1%／點'),
    ('poison', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '濃毒：開印那一擊附傷 ×1.5'),
    ('poison', 1, 1, 'B1'): (IMPL, 'ESSBElem3.OpenPoison', '毒膜：開印時你毒抗 +50% 5 秒'),
    ('poison', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '毒印記持續 +0.2 秒／點'),
    ('poison', 1, 2, 'B0'): (IMPL, 'ESSBElem3.OnFormOpened(8)', '毒臨強化：毒臨時範圍內敵人 +3 毒層'),
    ('poison', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '毒臨：開毒形態時對範圍內敵人各開印一次，2 公尺 +0.2 公尺／點'),
    ('poison', 1, 3, 'B0'): (IMPL, 'ESSBElem3.OpenPoison', '腐蝕開印：開印目標毒抗 -10% 8 秒'),
    ('poison', 1, 3, 'B1'): (IMPL, 'ESSBElem3.OpenPoison', '毒血：開印時你回血 B_max ×0.5'),
    ('poison', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('poison', 1, 4, 'B0'): (IMPL, 'ESSBElem3.OpenPoison', '劇毒之始：同調三段時開印毒層 ×2（再補一份等量的開印層數）'),
    ('poison', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('poison', 2, 0, 'B0'): (IMPL, 'ESSBElem3.CatalyzeRate → ESSBStatus.Tick', '潰爛：催毒期間每秒跳三次（基礎兩次）'),
    ('poison', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '毒印記的融斷 +2%／點'),
    ('poison', 2, 1, 'B0'): (IMPL, 'ESSBElem3.CatalyzeSeconds', '延毒：催毒 8 → 12 秒'),
    ('poison', 2, 1, 'B1'): (IMPL, 'ESSBElem3.EndPoisonNodes', '瘴氣：毒終焉時毒層以原層數複製到 6 公尺內 5 人（結清 engine-coverage 的「瘴氣複製」）'),
    ('poison', 2, 2, 'M'): (IMPL, 'ESSBElem.OnEnd → ESSBController.SetEndBoost / GetHitMult', '終焉後 5 秒內接管元素附傷 +1%／點'),
    ('poison', 2, 2, 'B0'): (IMPL, 'ESSBElem3.CatalyzeSeconds（aiReason == 1）', '毒斷：融斷的催毒持續 ×2'),
    ('poison', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '毒印記的融斷再 +2%／點'),
    ('poison', 2, 3, 'B0'): (IMPL, 'ESSBElem3.ApplyVirulence', '劇毒：催毒期間下一個等量於目標當前毒抗的削減，等效於「毒抗視為 0」（同碎冰碎甲的做法）'),
    ('poison', 2, 3, 'B1'): (IMPL, 'ESSBElem3.EndPoisonNodes', '腐蝕終焉：毒終焉後目標魔抗 -20% 8 秒'),
    ('poison', 2, 4, 'M'): (IMPL, 'ESSBElem3.PoisonTickMult（催毒中）', '催毒期間毒層傷害 +3%／點'),
    ('poison', 2, 4, 'B0'): (IMPL, 'ESSBElem3.EndPoisonNodes → ESSBController.StartDomain(8, 5)', '毒霧：毒印記融斷後 5 秒毒霧，內部每秒 +1 毒層'),

    # ================= 5.11 水（tree 8）
    ('water', 0, 0, 'M'): (IMPL, 'ESSBElem3.WetSeconds → ESSBStatus.Tick', '浸濕持續 10 秒 +0.3 秒／點'),
    ('water', 0, 0, 'B0'): (IMPL, 'ESSBElem3.OnWaterHit', '清流：命中回復耐力 5'),
    ('water', 0, 1, 'M'): (IMPL, 'ESSBElem3.FlowPercent → WaterFormTick', '長流：每秒回復最大生命與最大耐力的 0.3% +0.02%／點（自有效果，不動回復速率 AV）'),
    ('water', 0, 1, 'B0'): (IMPL, 'ESSBElem3.OnWaterHit + WaterHitMult', '水壓：命中浸濕目標 +1 水壓（狀態 kind 9），每層水附傷 +10%（結清 engine-coverage 的「水壓」）'),
    ('water', 0, 1, 'B1'): (IMPL, 'PERK ESSB_P_water_0_1_B2 進入點 0x24 分頁 1', '水膜：攻擊者帶本模組水印記效果時你受傷 -10%（分頁 1 是攻擊者，決定 61）'),
    ('water', 0, 2, 'M'): (IMPL, 'ESSBElem3.WaterHitMult', '水壓每層水附傷 +1%／點'),
    ('water', 0, 2, 'B0'): (IMPL, 'ESSBElem3.OnWaterHit → ESSBController.TakeCleanse / ApplyCleanse', '洗淨：命中時清除自身一個負面效果，每 3 秒一次；逐項 DispelSpell 自有減益 + Cure Disease（不用 Dispel 原型，絕不洗自己的增益）'),
    ('water', 0, 3, 'M'): (IMPL, 'ESSBElem3.FlowPercent', '同調每段長流回復 +0.05%／點'),
    ('water', 0, 3, 'B0'): (IMPL, 'ESSBElem3.OnWaterHit + ESSBGuard.OnHitEx + PERK ESSB_P_water_0_3_B1 進入點 0x24', '水鏡：每命中 +1 層（最多 3），被打消耗一層並抵消該次 30% 傷害（讀 ESSB_WaterMirror）'),
    ('water', 0, 3, 'B1'): (IMPL, 'ESSBController.ApplyCleanse(True) → DispelHostileEffects（SPEL ESSB_PurgeSpell）', '淨化：洗淨再加解毒，並用 PO3 GetActiveEffects 掃掉所有帶敵對／有害旗標的外來效果'),
    ('water', 0, 4, 'M'): (IMPL, 'ESSBElem3.FlowPercent / WaterFormTick', '長河：同調三段時長流再 +0.05%／點，且同時作用於 6 公尺內同伴'),
    ('water', 0, 4, 'B0'): (IMPL, 'PERK ESSB_P_water_0_4_B1 進入點 0x24 與 0x29', '水體：同調三段的水形態受傷 -15%，火傷減半（0x29 分頁 1 判入射效果的 MagicDamageFire）'),
    ('water', 1, 0, 'M'): (IMPL, 'ESSBElem3.WetSlow → ESSBReactions.Open', '浸濕減速 10% +1%／點'),
    ('water', 1, 0, 'B0'): (IMPL, 'ESSBElem3.OpenWater', '廣佈：開印時浸濕擴散到附近 1 人'),
    ('water', 1, 1, 'M'): (IMPL, 'ESSBElem3.WaterHitMult（GetOpenBoost）', '開印後 5 秒內水附傷 +1%／點'),
    ('water', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '深濕：開印那一擊附傷 ×1.5'),
    ('water', 1, 1, 'B1'): (IMPL, 'ESSBElem3.OpenWater', '回流：開印時回復耐力 15'),
    ('water', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '水印記持續 +0.2 秒／點'),
    ('water', 1, 2, 'B0'): (IMPL, 'ESSBElem3.OnFormOpened(9)', '水臨強化：水臨時範圍內敵人浸濕並減速 20%，你立即淨化'),
    ('water', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '水臨：開水形態時對範圍內敵人各開印一次，2 公尺 +0.2 公尺／點'),
    ('water', 1, 3, 'B0'): (IMPL, 'ESSBElem3.OpenWater → ESSBController.ApplyStrip（SPEL ESSB_StripSpell）', '沖刷：開印驅散目標一個有時限的增益，每目標 10 秒一次（自有 Dispel 原型，不影響常駐能力）'),
    ('water', 1, 3, 'B1'): (IMPL, 'ESSBElem3.OnWaterHit', '水牢：浸濕目標移速 -20% 3 秒'),
    ('water', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('water', 1, 4, 'B0'): (IMPL, 'ESSBElem3.OpenWater → ESSBController.SetWetLock → ESSBStatus', '汪洋之始：同調三段時開印的浸濕不過期，直到被切掉（ClearStack(8) 才解除）'),
    ('water', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('water', 2, 0, 'B0'): (IMPL, 'ESSBElem3.GuideMult', '強引：導引 ×1.5 → ×2.0'),
    ('water', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '水印記的融斷 +2%／點'),
    ('water', 2, 1, 'B0'): (IMPL, 'ESSBElem3.GuideSync → ESSBReactions.EndWater', '潮引：水終焉時接管元素 +5 → +10 同調'),
    ('water', 2, 1, 'B1'): (IMPL, 'ESSBElem3.EndWaterNodes', '水斷：水印記融斷改為治療你並回復耐力（各 B_max ×2.0）'),
    ('water', 2, 2, 'M'): (IMPL, 'ESSBElem.OnEnd → ESSBController.SetEndBoost', '終焉後 5 秒內接管元素附傷 +1%／點'),
    ('water', 2, 2, 'B0'): (IMPL, 'ESSBElem3.EndWaterNodes → ESSBController.KeepAsSecond', '汪洋：水終焉保留浸濕為副印記 10 秒，融斷時再結算一次'),
    ('water', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '水印記的融斷再 +2%／點'),
    ('water', 2, 3, 'B0'): (IMPL, 'ESSBElem3.EndWaterNodes → ESSBController.SetNextEndMultOn', '大潮：水終焉時 5 公尺內所有浸濕目標都拿到接管元素的導引'),
    ('water', 2, 3, 'B1'): (IMPL, 'ESSBElem3.EndWaterNodes', '洗滌：水終焉淨化你所有負面，並驅散目標一個有時限的增益'),
    ('water', 2, 4, 'M'): (IMPL, 'ESSBElem3.GuideMult（ESSBElem.SignatureMult）', '導引 +3%／點'),
    ('water', 2, 4, 'B0'): (IMPL, 'ESSBElem3.EndWaterNodes → ESSBController.StartDomain(9, 5)', '潮池：水印記融斷後 5 秒水域，內部敵人減速 30%、你每秒回血回耐'),

    # ================= 5.12 黑暗（tree 9）
    ('darkness', 0, 0, 'M'): (IMPL, 'ESSBElem3.ApplyCurseErosion', '詛咒每層抗性侵蝕 -（2% + 0.2%／點）：火冰電魔毒五種抗性，原型 34 會自己還原'),
    ('darkness', 0, 0, 'B0'): (IMPL, 'ESSBElem3.OnDarkHit', '蝕魔：命中吸魔 ×2；基礎的每擊吸魔取 B_max ×0.5，×2 即 ×1.0（解讀見實作紀錄）'),
    ('darkness', 0, 1, 'M'): (IMPL, 'ESSBElem3.DarkHitMult', '暗附傷 +1%／點'),
    ('darkness', 0, 1, 'B0'): (IMPL, 'ESSBElem3.OnDarkHit', '衰弱：詛咒目標攻擊 -10% 3 秒'),
    ('darkness', 0, 1, 'B1'): (IMPL, 'PERK ESSB_P_darkness_0_1_B2 進入點 0x24 分頁 1', '影甲：攻擊者帶本模組暗印記效果時你受傷 -10%'),
    ('darkness', 0, 2, 'M'): (IMPL, 'ESSBElem3.TargetDamageMult → ESSBController.ApplyDamage / GetHitMult', '詛咒滿層目標受所有傷害 +1%／點；只放大本模組造成的傷害（決定 61）'),
    ('darkness', 0, 2, 'B0'): (IMPL, 'ESSBElem3.OnDarkHit（ESSB_Util_HealRateDebuff）', '腐朽：詛咒目標受治療 -50%，以 HealRateMult -50% 表達（同血咒的偏離）'),
    ('darkness', 0, 3, 'M'): (IMPL, 'ESSBElem3.DarkHitMult', '同調每段暗附傷 +1%／點'),
    ('darkness', 0, 3, 'B0'): (IMPL, 'ESSBElem3.DarkHitMult → ESSBNoForm.IsSpellUser', '虛空：對魔力低於 25% 的施法者傷害 ×1.5'),
    ('darkness', 0, 3, 'B1'): (IMPL, 'ESSBElem3.OnKill', '收割：詛咒目標死亡回魔 B_max × 層數'),
    ('darkness', 0, 4, 'M'): (IMPL, 'ESSBElem3.CurseCap → ESSBController.StackCap', '深淵：同調三段時詛咒上限 +1／每 3 點（最多 +5，共 10）；抗性以 AV 負值侵蝕，本來就可為負'),
    ('darkness', 0, 4, 'B0'): (IMPL, 'ESSBGuard.OnHitEx → ESSBElem3.OnShadowBody + PERK ESSB_P_darkness_0_4_B1 進入點 0x24 ×0', '影身：同調三段時被近戰命中 30% 機率無效並回魔；擲中就開 2 秒受傷 ×0 視窗，抵掉下一次攻擊（同風的殘影）'),
    ('darkness', 1, 0, 'M'): (IMPL, 'ESSBElem3.OpenStacks → ESSBReactions.Open', '開印詛咒 2 層 +1／每 5 點'),
    ('darkness', 1, 0, 'B0'): (IMPL, 'ESSBElem3.OpenDark → ESSBController.ApplyFear（MGEF ESSB_FearEffect，原型 7）', '夢魘：開印施加恐懼；規劃的 1.5 秒取整為 2 秒（狀態與效果時長是整數秒）'),
    ('darkness', 1, 1, 'M'): (IMPL, 'ESSBElem3.DarkHitMult（GetOpenBoost）', '開印後 5 秒內暗附傷 +1%／點'),
    ('darkness', 1, 1, 'B0'): (IMPL, 'ESSBElem3.OpenDark → ESSBController.ApplyFrenzy（MGEF ESSB_FrenzyEffect，原型 8）', '瘋狂：開印使目標 3 秒內攻擊最近的任何人；等級上限與免疫判定同原版幻術'),
    ('darkness', 1, 1, 'B1'): (IMPL, 'ESSBElem3.OpenDark', '幻影：「目標對你的命中率 -30%」以攻擊 -30% 3 秒表達（引擎沒有命中率修正）'),
    ('darkness', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '暗印記持續 +0.2 秒／點'),
    ('darkness', 1, 2, 'B0'): (IMPL, 'ESSBElem3.OnFormOpened(10)', '暗臨強化：暗臨時範圍內敵人恐懼 2 秒'),
    ('darkness', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened', '暗臨：開暗形態時對範圍內敵人各開印一次，2 公尺 +0.2 公尺／點'),
    ('darkness', 1, 3, 'B0'): (IMPL, 'ESSBElem3.OpenDark → ESSBController.ApplySilenceSpell', '迷亂：開印目標 3 秒內無法施法，沿用沉默的實作（ESSBSilence + MagickaRateMult -100）'),
    ('darkness', 1, 3, 'B1'): (IMPL, 'ESSBElem3.OpenDark', '暗染：開印時附近 1 人也詛咒（連印記一起給）'),
    ('darkness', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('darkness', 1, 4, 'B0'): (IMPL, 'ESSBElem3.OpenDark', '群魔：同調三段時開印的瘋狂改為範圍（最多 5 人）'),
    ('darkness', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('darkness', 2, 0, 'B0'): (IMPL, 'ESSBElem3.AfterDeathCurse ← ESSBStatus.Tick', '饕餮：死咒結算時吸血吸魔各 B_max ×1.0'),
    ('darkness', 2, 0, 'B1'): (IMPL, 'ESSBElem3.Reanimate → ESSBController.ApplyReanimate（MGEF ESSB_ReanimateEffect，原型 22）', '亡者歸來：黑暗致死 25% 機率復生為僕從；六階等級上限 6／13／21／30／60／任意，持續 120／120／120／180／180／永久；計入召喚上限，必要角色與帶 MagicNoReanimate 的屍體不復生，化灰先於復生'),
    ('darkness', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '暗印記的融斷 +2%／點'),
    ('darkness', 2, 1, 'B0'): (IMPL, 'ESSBElem3.DeathCurseSeconds → ESSBReactions.EndDark', '不治：死咒的「無法被治療」3 → 6 秒；以 HealRateMult -100% 表達（結清 engine-coverage 的「死咒無法被治療」）'),
    ('darkness', 2, 1, 'B1'): (IMPL, 'ESSBElem3.EndDarkNodes → ESSBController.SetPendingDrain → ESSBElem3.OnAnyEnd', '蝕魔終焉：暗終焉後接管元素的下一次終焉附帶吸魔'),
    ('darkness', 2, 2, 'M'): (IMPL, 'ESSBElem3.DeathCurseLostRatio → ESSBStatus.Tick', '死咒的「已損失生命」係數 15% +0.5%／點'),
    ('darkness', 2, 2, 'B0'): (IMPL, 'ESSBElem3.AfterDeathCurse', '亡魂：死咒殺死目標時附近敵人恐懼 2 秒'),
    ('darkness', 2, 2, 'B1'): (IMPL, 'ESSBElem3.Reanimate（ESSB_Util_MeleeBuff）', '亡者強化：僕從繼承死前詛咒層數為攻擊加成（AV 34，每層 10 點，與「攻擊削弱」同一慣例），持續 ×2'),
    ('darkness', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '暗印記的融斷再 +2%／點'),
    ('darkness', 2, 3, 'B0'): (IMPL, 'ESSBElem3.AfterDeathCurse → ESSBController.Execute', '處刑：死咒結算時生命低於 15% 直接死亡；首領與必要角色改為 ×3 傷害'),
    ('darkness', 2, 3, 'B1'): (IMPL, 'ESSBElem3.EndDarkNodes', '深淵回響：暗終焉回滿你的魔力'),
    ('darkness', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult → ESSBReactions.EndDark', '死咒 +3%／點'),
    ('darkness', 2, 4, 'B0'): (IMPL, 'ESSBElem3.EndDarkNodes → ESSBController.StartDomain(10, 5)', '死域：暗印記融斷後 5 秒死域，內部敵人無法被治療、每秒受 B_max ×0.5 暗傷'),
    ('darkness', 2, 4, 'B1'): (IMPL, 'ESSBElem3.Reanimate', '死靈主：同調三段時亡者歸來機率 100%，任何等級可復生（第六階永久，上限 1 名）'),

    # ================= 5.13 星界（tree 10）
    ('astral', 0, 0, 'M'): (IMPL, 'ESSBElem3.AstralTickMult → ESSBStatus.Tick', '星痕延遲傷害 +2%／點'),
    ('astral', 0, 0, 'B0'): (IMPL, 'SPEL ESSB_Ability_Induction + ESSBController.RefreshAbilities', '星輝：星形態魔力回復 +20%；與雷樹「感應」效果完全相同，沿用同一個能力記錄不另建'),
    ('astral', 0, 1, 'M'): (IMPL, 'ESSBElem3.AstralHitMult', '星附傷 +1%／點'),
    ('astral', 0, 1, 'B0'): (IMPL, 'ESSBElem3.OnAstralHit → ESSBController.BumpAstralHits', '追擊：每第 3 次命中額外 35% 星傷（計數器離開形態清零）'),
    ('astral', 0, 1, 'B1'): (IMPL, 'ESSBElem3.OnAstralHit', '星軌：命中回復魔力 B_max'),
    ('astral', 0, 2, 'M'): (IMPL, 'ESSBElem3.AstralCap → ESSBController.StackCap', '星痕層數上限 3 +1／每 5 點'),
    ('astral', 0, 2, 'B0'): (IMPL, 'ESSBElem3.AstralHitMult', '星痕弱點：重擊時每層星痕 +8%'),
    ('astral', 0, 3, 'M'): (IMPL, 'ESSBElem3.AstralHitMult', '同調每段星附傷 +1%／點'),
    ('astral', 0, 3, 'B0'): (IMPL, 'ESSBElem3.AstralForesee ← ESSBStatus.Tick + PERK ESSB_P_astral_0_3_B1 進入點 0x24', '預知：環狀桶最後一格還有層數時開 2 秒視窗，引爆前那一秒你受傷 -20%'),
    ('astral', 0, 3, 'B1'): (IMPL, 'ESSBElem3.OnAstralDetonate', '星盾：星痕引爆時你獲得臨時生命護盾（AV 24，10 秒）'),
    ('astral', 0, 4, 'M'): (IMPL, 'ESSBElem3.FallChain / ConstellationRadius', '群星：同調三段時星落連鎖附近星痕目標，1 公尺 +1 公尺／點（夜晚 ×1.5）'),
    ('astral', 0, 4, 'B0'): (IMPL, 'ESSBElem3.OnAstralDetonate + PERK ESSB_P_astral_0_4_B1 進入點 0x29', '星體：同調三段的星形態魔法傷害 -30%，星痕引爆治療你'),
    ('astral', 1, 0, 'M'): (IMPL, 'ESSBElem3.AstralDelay → ESSBStatus.Tick', '星痕延遲 2 秒；10 點以上縮成 1 秒（狀態容器是整數秒 tick，只有兩檔）'),
    ('astral', 1, 0, 'B0'): (IMPL, 'ESSBElem3.OpenAstral / ScatterRadius', '星散：開印時附近 1 人也星痕，搜尋範圍 15 公尺 +1 公尺／點'),
    ('astral', 1, 1, 'M'): (IMPL, 'ESSBElem3.AstralHitMult（GetOpenBoost）', '開印後 5 秒內星附傷 +1%／點'),
    ('astral', 1, 1, 'B0'): (IMPL, 'ESSBElem.OpenStrikeMult', '明星：開印那一擊附傷 ×1.5'),
    ('astral', 1, 1, 'B1'): (IMPL, 'ESSBElem3.OpenAstral', '星引力：開印時回復魔力 B_max'),
    ('astral', 1, 2, 'M'): (IMPL, 'ESSBElem.MarkDurationBonus', '星印記持續 +0.2 秒／點'),
    ('astral', 1, 2, 'B0'): (IMPL, 'ESSBElem3.OnFormOpened(11)', '星臨強化：星臨時範圍內敵人星痕 2 層（範圍同星臨）'),
    ('astral', 1, 3, 'M'): (IMPL, 'ESSBElem.OnFormOpened → ESSBElem3.AdventRadius', '星臨：2 公尺 +1 公尺／點（其他元素是 +0.2），夜晚再 ×1.5'),
    ('astral', 1, 3, 'B0'): (IMPL, 'ESSBElem3.OpenAstral → ESSBController.SetStarLock → ESSBElem3.TargetDamageMult', '星鎖：開印目標 3 秒內受所有元素傷 +10%；只放大本模組造成的傷害（決定 61）'),
    ('astral', 1, 3, 'B1'): (IMPL, 'ESSBElem3.OpenAstral + PERK ESSB_P_astral_1_3_B2 進入點 0x24', '星光：開印時你受傷 -10% 3 秒（讀 ESSB_GuardStar）'),
    ('astral', 1, 4, 'M'): (IMPL, 'ESSBElem.OpenMult', '開印效果 +3%／點'),
    ('astral', 1, 4, 'B0'): (IMPL, 'ESSBElem3.OpenAstral', '星耀：同調三段時開印的延遲星傷改為立即並 ×2'),
    ('astral', 2, 0, 'M'): (IMPL, 'ESSBElem.EndMult', '終焉 +2%／點'),
    ('astral', 2, 0, 'B0'): (IMPL, 'ESSBElem3.FallK', '隕星：星落 ×2.0 → ×3.0'),
    ('astral', 2, 1, 'M'): (IMPL, 'ESSBElem.BurstMult', '星印記的融斷 +2%／點'),
    ('astral', 2, 1, 'B0'): (IMPL, 'ESSBElem3.HasMeteorShower / FallRadius', '流星雨：星落改為範圍（3 公尺，隨關閉專精主線每點 +0.8 公尺，夜晚 ×1.5，最多 5 人）'),
    ('astral', 2, 1, 'B1'): (IMPL, 'ESSBElem3.Fall → ESSBController.ApplyTrueDamage(amount, target, 10)', '星斷：星印記融斷改為真實傷害 ×0.6，以星樹的 G(L) 計（不吃無元素樹的破魔加成）'),
    ('astral', 2, 2, 'M'): (IMPL, 'ESSBElem3.FallRadius', '星落與星域的範圍 3 公尺 +0.8 公尺／點（星落需「流星雨」才有範圍）'),
    ('astral', 2, 2, 'B0'): (IMPL, 'ESSBElem3.EndAstralNodes → ESSBController.AddSync(10)', '星引：星終焉後接管元素 +10 同調'),
    ('astral', 2, 3, 'M'): (IMPL, 'ESSBElem.BurstMult', '星印記的融斷再 +2%／點'),
    ('astral', 2, 3, 'B0'): (IMPL, 'ESSBElem3.EndAstralNodes → ESSBController.BoostSyncToStage1', '星界之門：星終焉後把同調拉到一段門檻（讀 ESSB_SyncT1），接管元素直接從一段起跳'),
    ('astral', 2, 3, 'B1'): (IMPL, 'ESSBElem3.TakeoverOpenMult → ESSBReactions.EndAstral', '星軌終焉：接管元素的開印 ×1.5 → ×2.0（基礎星落本來就給 ×1.5，分支再加深，解讀見實作紀錄）'),
    ('astral', 2, 4, 'M'): (IMPL, 'ESSBElem.SignatureMult → ESSBElem3.Fall', '星落 +3%／點'),
    ('astral', 2, 4, 'B0'): (IMPL, 'ESSBElem3.EndAstralNodes → ESSBController.StartDomain(11, 5, FallRadius)', '星域：星印記融斷後 5 秒星域，範圍同星落，內部敵人受所有元素傷 +20%（結清 engine-coverage 的「星界範圍成長」與「夜晚 ×1.5」）'),
}

# ------------------------------------------------------------------ 共通機制（規劃 1.1、2.x）
MECHANISMS = [
    ('fix8 addition', '無形態基礎真傷（文件化新增，非規劃節點）', IMPL,
     'ESSBController.OnWeaponHit → OnNoFormHit → ApplyNoFormBaseline → ApplyTrueDamage',
     '使用者核准新增：每次通過元素附傷共用資格檢查的無形態命中，'
     'noform_base_true（預設 5）× G(L_無元素) × ESSB_BaseDamageMult；重擊 ×1.5。'
     'G 與傷害倍率各一次，額外 XP 為 0；保留純武藝／破魔節點的獨立效果。'),
    ('1.1', '開形態需要魔力高於上限 10%；切換不檢查', IMPL,
     'ESSBController.ToggleForm', '順轉與免門檻兩個節點可以豁免'),
    ('1.1', '血位：三條曲線線性內插（命中倍率、吸血、損血）', IMPL,
     'ESSBController.GetBloodHitMult / GetBloodLeechRatio / ESSBFormRules', '損血在 ESSBFormRules 每秒扣，命中倍率乘在 GetDamageMult'),
    ('1.1', '風形態潛行：潛行攻擊時風附傷 ×3', IMPL,
     'ESSBController.ApplyProc', '讀 HitData 的潛行旗標（2048）；移速與 Muffle 的自有能力屬風樹，round 2'),
    ('1.1', '火形態過熱：同調三段後每命中 +1，滿了自爆或熔身', IMPL,
     'ESSBController.HitStacks / AddSelf(4)', '上限由 ESSBElem.OverheatCap（熔爐 20），熔身分支改為 10 秒增益'),
    ('2.1', '每擊隨機 B：各元素自己的常態範圍，重擊 ×1.5', IMPL,
     'ESSBReactions.RollBase / ESSBController.ApplyProc', '規劃 2.1 的 11 組上下限；施放前 SetNthEffectMagnitude，取代原本寫死的 8/12'),
    ('2.1', '雷的附傷另削減目標魔力 50%', IMPL,
     'ESSBElem.Discharge（放電）', '規劃 2.6 的感電與放電都削魔；電蝕分支改為 100%'),
    ('2.3', '狀態上限的三種來源：基礎、分支、通用樹「萬象」欄', IMPL,
     'ESSBController.StackCap + ESSBNodes.StatusCapBonus', '量表類（凍結）固定 5，不吃通用樹加成'),
    ('2.7', 'G(L) = 1 + 0.05 × L', IMPL,
     'ESSBTrees.TreeG → ESSBController.ApplyDamage / ApplyProc / ApplyTrueDamage', '反應、DoT、附傷、真傷四條路徑都在同一處乘，不重複'),
    ('2.7', 'M_mod 只乘一次，不出現疊乘', IMPL,
     'ESSBController.GetHitMult / ESSBReactions.End', '附傷 = 共通 × 通用樹 × 元素樹；終焉 = 共通 × 通用樹關閉 × 元素樹關閉'),
    ('2.8', '真實傷害類別：不吃護甲、抗性、外部加成', IMPL,
     'MGEF ESSB_TrueEffect（skill = -1、resist = None）+ ESSBController.ApplyTrueDamage', '只掛 ESSB_TrueDamage keyword，沒有外部天賦認得；造成真傷練無元素樹'),
    ('2.9', '融斷後留下的領域（火域、冰原）', IMPL,
     'ESSBController.StartDomain / InDomain / TickDomain', '不放 ObjectReference、不用 hazard 或爆炸：只記中心座標與剩餘秒數，判定在既有的每秒 tick 與命中路徑上做'),
    ('2.9', '各元素的「臨」：以玩家為中心 2 公尺 + 0.2 公尺／點', IMPL,
     'ESSBElem.OnFormOpened → ESSBController.ForceOpenOn', '火冰雷已落地，其餘元素同一個函式'),
    ('2.13', '附傷、反應、真傷的學派歸屬與 DoCombatSpellApply', IMPL,
     'build_v03（SCHOOLS/casting_perks）+ ESSBController', '真傷刻意不掛學派；其餘沿用引擎前線的配置'),
    ('6.1', '每個節點效果處理函式都留紀錄', IMPL,
     'ESSBController.LogThrottled / ESSBLog.Log', '等級 1 事件（開印、終焉、融斷、化身、處決、沉默、反咒、領域）、等級 2 節點、等級 3 公式細項'),
    ('8', '碎冰處決以自有高強度傷害法術執行，不用 Kill()', IMPL,
     'ESSBController.Execute', '擊殺歸屬與死亡事件與一般擊殺一致；首領與必要角色由呼叫端改走 ×5 傷害'),
    ('8', '過熱／熱度／電荷等自身資源鏡射成全域變數', IMPL,
     'ESSBController.PushSelf / PushSyncStage / SetGlobal', 'PERK 進入點的 CTDA 只讀得到全域變數，這是樣式 C 的橋'),
    # ---- 機制前線 round 2
    ('1.1', '血形態維持費：依血位曲線每秒扣最大生命（1.0%／0.6%／0.2%／0）', IMPL,
     'ESSBController.BloodDrainPerSecond / PayBloodCost → ESSBFormRules.OnUpdate',
     'round 1 是固定 0.5%，本輪換成 1.1 的四點曲線；血氣減半、血臨強化／血約／不死歸零；永遠留 1 點生命'),
    ('1.1', '血形態重擊不消耗耐力，改扣生命（8%／5%／2%／0）', IMPL,
     'PERK ESSB_P_BaseRules 進入點 0x1B ×0 + ESSBController.PayBloodCost（OnWeaponHit）',
     '耐力那一半用進入點（條件 ESSB_FormActive == 1 且 ESSB_CurrentElement == 6），生命那一半在命中時扣'),
    ('1.1', '風形態：移速 +10%、潛行腳步聲減半、潛行攻擊風附傷 ×3 且風勢直接滿', IMPL,
     'ESSBController.RefreshWindAbilities / RefreshWindStealth / ElementHitHook',
     'SPEL ESSB_Ability_WindSpeed（AV 30）與 ESSB_Ability_Muffle（AV 92）；潛行狀態在既有的每秒 tick 讀一次'),
    ('2.3', '土 岩甲：護甲加成、被打 -1、離開形態清空', IMPL,
     'ESSBController.SyncRockArmor / ConsumeRockArmor ← ESSBGuard.OnHitEx',
     '護甲用自有的 ESSB_Util_ArmorBuff（AV 39、原型 34），層數變動時重下、歸零時 DispelSpell'),
    ('2.3', '風 風勢：到門檻送出風刃後歸零', IMPL,
     'ESSBElem2.CheckWindGauge ← ESSBController.ElementHitHook', '門檻 4（亂舞 3），送出後 ClearSelf(3)'),
    ('2.3', '風 失衡：受風刃傷害 +30%', IMPL,
     'ESSBElem2.WindBladeOne', '在風刃的傷害計算裡讀 GetStack(target, 4)，不需要 PERK 進入點'),
    ('2.6', '土 地震的「耐力歸零跌倒」', IMPL,
     'ESSBElem2.QuakeOne → ESSBController.Knockdown', 'PushActorAway 力道 3.0，每目標 8 秒一次；免疫者改為減速 30% 3 秒'),
    ('2.6', '風 開印的「拉近 1.5–3 公尺」與終焉的「吹飛 3–6 公尺」', IMPL,
     'ESSBController.PullIn / PullTo / BlowBack（ApplyHavokImpulse）',
     '拉近每目標 3 秒一次、吹飛每目標 8 秒一次；免疫名單＝龍、騎乘中、必要角色與首領、巨人與猛獁'),
    ('2.5', '風印記融斷的「吹上天」與落地傷害', IMPL,
     'ESSBController.LiftUp → ESSBStatus 浮空 → ESSBController.OnLanding',
     '浮空是自有的 2 秒狀態（規劃 8：不讀物理狀態），落地傷害在狀態到期的那一秒結算'),
    ('2.6', '聖 開印「目標受聖傷 +20%」', IMPL,
     'ESSBElem2.HolyVulnerability', '附傷與裁決共用同一個函式；沒有用 PERK 進入點，因為武器傷害的條件分頁讀不到目標'),
    ('2.7', '血承：擊殺時吸收死者屬性 15 秒', IMPL,
     'ESSBController.ApplyInherit（SPEL ESSB_InheritSpell 的 7 個 Peak Value Modifier）',
     '火冰電毒魔抗各 50%、護甲 20%、最大生命 10%；施放前逐一 SetNthEffectMagnitude，重掛即取代'),
    ('2.10', '白天 → 化灰必定觸發', IMPL,
     'ESSBElem2.ShouldAsh → ESSBController.ApplyAsh', '化灰 MGEF 的 DATA 照抄原版 PerkDisintegrateFFAimed；龍與必要角色不化灰'),
    ('8', '死靈施法者判定（原版無關鍵字，候選三選一）', IMPL,
     'ESSBController.IsNecromancer',
     '取三個候選的聯集：職業 CombatMageNecro（0x0C969F）、陣營 NecromancerFaction（0x034B74）、PO3 GetCommandedActors 非空'),
    ('8', 'SpeedMult 修正的重新整理方式', IMPL,
     'ESSBController.RefreshSpeed',
     '所有移速修正都走 MGEF（同原版 FrostSlowFFContact，AV 30 + 原型 34），不用 SetActorValue；'
     '另加一次負重微調（ModActorValue CarryWeight +0.1 / -0.1，淨值為零）強迫重算衍生數值，只在形態開／切／關時跑'),
    ('8', '「不解除潛行」用壓低偵測值實作', IMPL,
     'ESSBController.KeepSneak / TickTimers（PO3 PreventActorDetection / ResetActorDetection）',
     '擊殺後 5 秒，尊重原版偵測系統，不鎖 AI、不動 AI 套件'),
    ('2.9', '玩家受擊事件（PO3 OnHitEx）與擊殺事件（OnActorKilled）', IMPL,
     'ESSBGuard', '第三個 Player 別名腳本；每攻擊者 3 秒冷卻的 4 格環；擊殺仍保留控制器每秒 tick 的後援路徑'),
    # ---- 機制前線 round 3
    ('2.3', '毒 毒層：無上限、每層獨立 6 秒、≥門檻自動擴散', IMPL,
     'ESSBStatus.Tick（六格環狀桶）+ ESSBElem3.SpreadInterval / SpreadThreshold / SpreadTargets '
     '+ ESSBController.SpreadPoison',
     '命中不刷新舊層；催毒只加速不清除；擴散每次只找一個對象，不做全場掃描'),
    ('2.3', '水 水壓：命中浸濕目標 +1，每層水附傷 +10%', IMPL,
     'ESSBElem3.OnWaterHit / WaterHitMult / PressureCap → ESSBController.StackCap(9)',
     '結清引擎前線預留的狀態 kind 9；8 秒、命中刷新，上限 5（萬象 8）'),
    ('2.3', '暗 詛咒：上限 5，深淵在同調三段 +1／每 3 點（最多 10）', IMPL,
     'ESSBElem3.CurseCap → ESSBController.StackCap(10)', '侵蝕用原型 34 的抗性負向修正，會自己還原'),
    ('2.3', '星 星痕：每層 2 秒後自行引爆，上限 3 +1／每 5 點', IMPL,
     'ESSBStatus.Tick（兩格環狀桶）+ ESSBElem3.AstralDelay / AstralCap',
     '延遲只有 2 秒與 1 秒兩檔（狀態容器是整數秒 tick）'),
    ('2.6', '暗 死咒期間目標無法被治療', IMPL,
     'ESSBReactions.EndDark → ESSBController.ApplyUtil(20, 100%)',
     '引擎沒有「受到的治療」修正，以 HealRateMult -100% 表達（同血咒的偏離）；不治分支延長到 6 秒'),
    ('2.9', '瘴氣複製：中心為目標、6 公尺、5 人', IMPL,
     'ESSBElem3.EndPoisonNodes', '結清 engine-coverage 例外表的最後一條毒素項'),
    ('2.9', '星界的所有範圍：基礎相同，主線每點 +1 公尺', IMPL,
     'ESSBElem3.Range / AdventRadius / FallRadius / ConstellationRadius / ScatterRadius',
     '人數上限仍是 5（規劃 2.9），靠人數限制不靠距離'),
    ('2.9', '領域格從 1 格擴充為固定 3 格', IMPL,
     'ESSBController.StartDomain / InDomain / DomainActive / TickDomain / DomainFlag',
     '不同元素的領域在正常玩法下會同時存在（融斷留下領域 → 切換 → 再融斷）；'
     '同元素取代自己那一格，全滿時換掉剩餘秒數最少的；每秒仍然只掃一次 5 人；每格有自己的半徑'),
    ('2.10', '夜晚 → 星界所有範圍 ×1.5', IMPL,
     'ESSBElem3.Range → ESSBController.IsEnvNight', '與「夜晚黑暗附傷 +20%」同一個環境旗標'),
    ('8', '長流：自有的每秒百分比回復，不動回復速率 AV', IMPL,
     'ESSBElem3.WaterFormTick ← ESSBController.Tick',
     '掛在既有的每秒 tick，不另開計時器；不受原版戰鬥中回復減半影響'),
    ('8', '洗淨／淨化：不洗掉自己的增益', IMPL,
     'ESSBController.ApplyCleanse + DispelHostileEffects；SPEL ESSB_CleanseSpell / '
     'ESSB_PurgeSpell 只掛 Cure Disease（原型 3）與 Cure Poison（原型 29）',
     '特效前線改成「安全建構」：不依賴原型 2 與旗標 0x100（兩者都是推論值）。'
     '(1) 逐個 DispelSpell 本模組自己的有時限減益（SelfCleanseSpells，11 個）；'
     '(2) 治病與解毒走實測原型；(3) 淨化另用 PO3 GetActiveEffects 挑敵對／有害旗標的效果，'
     'GetMagicEffectSource 回推來源法術後 DispelSpell。最壞情況是少清幾個外來減益，'
     '不可能洗掉形態能力、血承、岩甲。MGEF ESSB_CleanseEffect / ESSB_PurgeEffect 仍在 ESP 裡待命'),
    ('8', '沖刷：對目標的 Dispel 原型，只影響有時限的法術效果', IMPL,
     'MGEF ESSB_StripEffect + ESSBController.ApplyStrip',
     '每目標 10 秒一次（沿用推力環狀表的 kind 2）；不影響能力型常駐效果；'
     'TARGET 路徑才留無限定 Dispel，ApplyStrip 硬性擋掉「目標＝玩家」與非法目標'),
    ('8', '亡者歸來：自有 Reanimate 原型的六階表，尊重召喚上限', IMPL,
     'MGEF ESSB_ReanimateEffect（原型 22、skill 19、magnitude ＝ 等級上限）'
     '+ ESSBElem3.Reanimate + ESSBController.SummonCap / ServantCount / CanReanimate',
     '上限 = 1（原版雙魂 0x0D5F1C 為 2），用 PO3 GetCommandedActors 計數；'
     '必要角色、龍、帶 MagicNoReanimate 的屍體不復生；化灰先於復生判定；第六階永久上限 1 名'),
    ('6', '恐懼與瘋狂：自有效果、等級上限、尊重免疫', IMPL,
     'MGEF ESSB_FearEffect（原型 7）／ESSB_FrenzyEffect（原型 8）'
     '+ ESSBController.ApplyFear / ApplyFrenzy / CanCharm',
     'magnitude 就是可影響的最高等級（10 + 暗樹等級），做法同原版幻術；'
     '首領與必要角色、龍、亡靈魔族免疫；只在黑暗樹出現'),
]


def rows(plan):
    """把 plan 的 495 個節點展開成覆蓋列；NODES 缺任何一個節點就回報 missing 讓建置失敗。"""
    out = []
    missing = []
    for tree in plan['trees']:
        tree_id = tree['id']
        # round 3 收尾：三輪都結束了，任何樹缺一個節點狀態都讓建置失敗（default = None）。
        # R2／R3 兩個常數保留給覆蓋表的圖例與歷史比對用。
        default = None
        for route in tree['routes']:
            for tier in route['tiers']:
                cells = [('M', tier['main'])]
                cells += [(f"B{b['index']}", b['description']) for b in tier['branches']]
                for slot, text in cells:
                    key = (tree_id, route['index'], tier['index'], slot)
                    found = NODES.get(key, default)
                    if found is None:
                        missing.append(key)
                        continue
                    status, where, note = found
                    if slot == 'M':
                        edid = f"ESSB_P_{tree_id}_{route['index']}_{tier['index']}_M1"
                    else:
                        edid = f"ESSB_P_{tree_id}_{route['index']}_{tier['index']}_B{int(slot[1:]) + 1}"
                    out.append({
                        'kind': 'node',
                        'section': tree['section'],
                        'tree': tree_id,
                        'route': route['name'],
                        'tier': tier['name'],
                        'slot': slot,
                        'edid': edid,
                        'text': text,
                        'status': status,
                        'where': where,
                        'note': note,
                    })
    for section, item, status, where, note in MECHANISMS:
        out.append({
            'kind': 'mechanism',
            'section': section,
            'tree': '-',
            'route': '-',
            'tier': '-',
            'slot': '-',
            'edid': '-',
            'text': item,
            'status': status,
            'where': where,
            'note': note,
        })
    return out, missing
