#pragma once
// Generated by build/fix19_native.py from build_v03.py and settings.json. Do not edit.
#include "Selection.h"
#include <string_view>
namespace essb {
struct Row { Key key; std::uint32_t id; std::string_view name; };
inline constexpr Row rows[]={
    {{1,0,0,0,0},0xb00,"ESSB_Hit_Fire_Normal"},
    {{1,1,0,0,0},0xb01,"ESSB_Hit_Fire_Power"},
    {{2,0,0,0,0},0xb02,"ESSB_Hit_Frost_Normal"},
    {{2,1,0,0,0},0xb03,"ESSB_Hit_Frost_Power"},
    {{4,0,0,0,0},0xb06,"ESSB_Hit_Earth_Normal"},
    {{4,1,0,0,0},0xb07,"ESSB_Hit_Earth_Power"},
    {{5,0,0,0,0},0xb08,"ESSB_Hit_Wind_Normal"},
    {{5,1,0,0,0},0xb09,"ESSB_Hit_Wind_Power"},
    {{6,0,0,0,0},0xb0a,"ESSB_Hit_Blood_Normal"},
    {{6,1,0,0,0},0xb0b,"ESSB_Hit_Blood_Power"},
    {{7,0,0,0,0},0xb0c,"ESSB_Hit_Divine_Normal"},
    {{7,1,0,0,0},0xb0d,"ESSB_Hit_Divine_Power"},
    {{8,0,0,0,0},0xb0e,"ESSB_Hit_Poison_Normal"},
    {{8,1,0,0,0},0xb0f,"ESSB_Hit_Poison_Power"},
    {{9,0,0,0,0},0xb10,"ESSB_Hit_Water_Normal"},
    {{9,1,0,0,0},0xb11,"ESSB_Hit_Water_Power"},
    {{10,0,0,0,0},0xb12,"ESSB_Hit_Darkness_Normal"},
    {{10,1,0,0,0},0xb13,"ESSB_Hit_Darkness_Power"},
    {{11,0,0,0,0},0xb14,"ESSB_Hit_Astral_Normal"},
    {{11,1,0,0,0},0xb15,"ESSB_Hit_Astral_Power"},
    {{5,0,1,0,0},0x5240,"ESSB_Hit_Wind_SneakNormal"},
    {{6,0,0,1,0},0x5241,"ESSB_Hit_Blood_Normal_B1"},
    {{6,0,0,2,0},0x5242,"ESSB_Hit_Blood_Normal_B2"},
    {{6,0,0,3,0},0x5243,"ESSB_Hit_Blood_Normal_B3"},
    {{3,0,0,0,1},0x5244,"ESSB_Hit_Lightning_Normal_R1"},
    {{3,0,0,0,2},0x5245,"ESSB_Hit_Lightning_Normal_R2"},
    {{3,0,0,0,3},0x5246,"ESSB_Hit_Lightning_Normal_R3"},
    {{3,0,0,0,4},0x5247,"ESSB_Hit_Lightning_Normal_R4"},
    {{3,0,0,0,5},0x5248,"ESSB_Hit_Lightning_Normal_R5"},
    {{5,1,1,0,0},0x524a,"ESSB_Hit_Wind_SneakPower"},
    {{6,1,0,1,0},0x524b,"ESSB_Hit_Blood_Power_B1"},
    {{6,1,0,2,0},0x524c,"ESSB_Hit_Blood_Power_B2"},
    {{6,1,0,3,0},0x524d,"ESSB_Hit_Blood_Power_B3"},
    {{3,1,0,0,1},0x524e,"ESSB_Hit_Lightning_Power_R1"},
    {{3,1,0,0,2},0x524f,"ESSB_Hit_Lightning_Power_R2"},
    {{3,1,0,0,3},0x5250,"ESSB_Hit_Lightning_Power_R3"},
    {{3,1,0,0,4},0x5251,"ESSB_Hit_Lightning_Power_R4"},
    {{3,1,0,0,5},0x5252,"ESSB_Hit_Lightning_Power_R5"},
};
constexpr const Row* row(Key k) noexcept { if(!k.element) return nullptr; for(auto& r:rows) if(r.key==k) return &r; return nullptr; }
constexpr std::uint32_t spell(Key k) noexcept { auto r=row(k); return r ? r->id : 0; }
inline constexpr std::uint32_t ESSB_Enabled=0x810;
inline constexpr std::uint32_t ESSB_FormActive=0x813;
inline constexpr std::uint32_t ESSB_CurrentElement=0x812;
inline constexpr std::uint32_t ESSB_DebugLevel=0x811;
inline constexpr std::uint32_t ESSB_NativeHit=0x52d1;
inline constexpr std::uint32_t ESSB_NativeWanted=0x52d2;
inline constexpr std::string_view elementNames[12]={"","火焰","冰霜","雷電","大地","風","鮮血","神聖","毒素","水","黑暗","星界"};
inline constexpr char nativeVersion[]="0.19.1";
inline constexpr char addressHash[]="1d7530d001139ca58f462ea0210a8055868159057ba8b5ebc624fc5e9c4f5e9a";
}
