#pragma once
// Generated by build/fix19_native.py from build_v03.py, build/fix20_records.py and settings.json. Do not edit.
#include "NodeIds.h"
#include <cstdint>
#include <string_view>
namespace essb {

struct ProcRow { int element; int power; std::uint32_t id; std::string_view name; };
// Element proc spells: element x normal / power (build/fix18_records.py variants).
inline constexpr ProcRow procRows[] = {
    {1, 0, 0xb00, "ESSB_Hit_Fire_Normal"},
    {1, 1, 0xb01, "ESSB_Hit_Fire_Power"},
    {2, 0, 0xb02, "ESSB_Hit_Frost_Normal"},
    {2, 1, 0xb03, "ESSB_Hit_Frost_Power"},
    {3, 0, 0xb04, "ESSB_Hit_Lightning_Normal"},
    {3, 1, 0xb05, "ESSB_Hit_Lightning_Power"},
    {4, 0, 0xb06, "ESSB_Hit_Earth_Normal"},
    {4, 1, 0xb07, "ESSB_Hit_Earth_Power"},
    {5, 0, 0xb08, "ESSB_Hit_Wind_Normal"},
    {5, 1, 0xb09, "ESSB_Hit_Wind_Power"},
    {6, 0, 0xb0a, "ESSB_Hit_Blood_Normal"},
    {6, 1, 0xb0b, "ESSB_Hit_Blood_Power"},
    {7, 0, 0xb0c, "ESSB_Hit_Divine_Normal"},
    {7, 1, 0xb0d, "ESSB_Hit_Divine_Power"},
    {8, 0, 0xb0e, "ESSB_Hit_Poison_Normal"},
    {8, 1, 0xb0f, "ESSB_Hit_Poison_Power"},
    {9, 0, 0xb10, "ESSB_Hit_Water_Normal"},
    {9, 1, 0xb11, "ESSB_Hit_Water_Power"},
    {10, 0, 0xb12, "ESSB_Hit_Darkness_Normal"},
    {10, 1, 0xb13, "ESSB_Hit_Darkness_Power"},
    {11, 0, 0xb14, "ESSB_Hit_Astral_Normal"},
    {11, 1, 0xb15, "ESSB_Hit_Astral_Power"},
};

// Spell per planned cast (HitMath.h Cast). Local FormIDs in Elements Spellblade.esp.
namespace spell {
inline constexpr std::uint32_t kDrainMagicka = 0x10a2;  // ESSB_Util_DrainMagicka
inline constexpr std::uint32_t kDrainStamina = 0x10a3;  // ESSB_Util_DrainStamina
inline constexpr std::uint32_t kHeal = 0x10a4;  // ESSB_Util_RestoreHealth
inline constexpr std::uint32_t kRestoreMagicka = 0x10a5;  // ESSB_Util_RestoreMagicka
inline constexpr std::uint32_t kRestoreStamina = 0x10a6;  // ESSB_Util_RestoreStamina
inline constexpr std::uint32_t kTrueDamage = 0x5021;  // ESSB_TrueDamageSpell
inline constexpr std::uint32_t kDispelMark = 0x5023;  // ESSB_ManaBreakSpell
inline constexpr std::uint32_t kSpendMagicka = 0x5301;  // ESSB_Native_SpendMagicka
inline constexpr std::uint32_t kBloodGuard = 0x5304;  // ESSB_BloodGuard
inline constexpr std::uint32_t kHushSpent = 0x5343;  // ESSB_HushSpent
inline constexpr std::uint32_t kSilence[8] = {0x5310, 0x5311, 0x5312, 0x5313, 0x5314, 0x5315, 0x5316, 0x5317};  // ESSB_Native_Silence_1..8
inline constexpr std::uint32_t kSoak[30] = {0x5320, 0x5321, 0x5322, 0x5323, 0x5324, 0x5325, 0x5326, 0x5327, 0x5328, 0x5302, 0x5329, 0x532a, 0x532b, 0x532c, 0x532d, 0x532e, 0x532f, 0x5330, 0x5331, 0x5332, 0x5333, 0x5334, 0x5335, 0x5336, 0x5337, 0x5338, 0x5339, 0x533a, 0x533b, 0x533c};  // soaked slow of 1..30 s: ESSB_Native_Soak_<s>, 10 s = ESSB_Native_SoakSlow
}  // namespace spell

// Effects the DLL looks for on the target or the player.
namespace effect {
inline constexpr std::uint32_t kBloodMark = 0x1005;  // ESSB_MarkEffect_Blood
inline constexpr std::uint32_t kSilence = 0x5024;  // ESSB_SilenceEffect
inline constexpr std::uint32_t kBloodGuard = 0x5303;  // ESSB_BloodGuardEffect
inline constexpr std::uint32_t kEchoPending = 0x5305;  // ESSB_EchoPendingEffect
inline constexpr std::uint32_t kTwinWindow = 0x5307;  // ESSB_TwinWindowEffect
inline constexpr std::uint32_t kRiposteWindow = 0x5344;  // ESSB_RiposteWindowEffect
inline constexpr std::uint32_t kHush = 0x5340;  // ESSB_HushEffect
inline constexpr std::uint32_t kHushSpent = 0x5342;  // ESSB_HushSpentEffect
}  // namespace effect

namespace glob {
inline constexpr std::uint32_t kEnabled = 0x810;  // ESSB_Enabled
inline constexpr std::uint32_t kFormActive = 0x813;  // ESSB_FormActive
inline constexpr std::uint32_t kCurrentElement = 0x812;  // ESSB_CurrentElement
inline constexpr std::uint32_t kDebugLevel = 0x811;  // ESSB_DebugLevel
inline constexpr std::uint32_t kNativeHit = 0x52d1;  // ESSB_NativeHit
inline constexpr std::uint32_t kNativeWanted = 0x52d2;  // ESSB_NativeWanted
inline constexpr std::uint32_t kBaseDamageMult = 0x515a;  // ESSB_BaseDamageMult
inline constexpr std::uint32_t kNodeScale = 0x515c;  // ESSB_NodeScale
inline constexpr std::uint32_t kMultDrain = 0x516b;  // ESSB_MultDrain
inline constexpr std::uint32_t kMultRecovery = 0x516a;  // ESSB_MultRecovery
inline constexpr std::uint32_t kMultDuration = 0x516c;  // ESSB_MultDuration
inline constexpr std::uint32_t kSlowCapPct = 0x5165;  // ESSB_SlowCapPct
inline constexpr std::uint32_t kWaterWetSlowPct = 0x5163;  // ESSB_WaterWetSlowPct
inline constexpr std::uint32_t kWaterClearStamina = 0x5166;  // ESSB_WaterClearStamina
inline constexpr std::uint32_t kManabreakMaxmagPct = 0x515f;  // ESSB_ManabreakMaxmagPct
inline constexpr std::uint32_t kSyncStage = 0x5000;  // ESSB_SyncStage
inline constexpr std::uint32_t kPrevElement = 0x5008;  // ESSB_PrevElement
inline constexpr std::uint32_t kTwinElement = 0x5009;  // ESSB_TwinElement
inline constexpr std::uint32_t kEnvWet = 0x1f13;  // ESSB_EnvWet
inline constexpr std::uint32_t kEnvNight = 0x1f15;  // ESSB_EnvNight
inline constexpr std::uint32_t kTreeLevel[13] = {0x2400, 0x2401, 0x2402, 0x2403, 0x2404, 0x2405, 0x2406, 0x2407, 0x2408, 0x2409, 0x240a, 0x240b, 0x240c};  // ESSB_Lvl_<tree>
}  // namespace glob

// Skyrim.esm forms (local FormIDs in Skyrim.esm).
namespace vanilla {
inline constexpr std::uint32_t kUndeadKeyword = 0x13796;  // KYWD
inline constexpr std::uint32_t kDaedraKeyword = 0x13797;  // KYWD
inline constexpr std::uint32_t kArmorSpellKeyword = 0x1ea72;  // KYWD
inline constexpr std::uint32_t kCloakKeyword = 0xb62e4;  // KYWD
inline constexpr std::uint32_t kNecroClass = 0xc969f;  // CLAS
inline constexpr std::uint32_t kNecroFaction = 0x34b74;  // FACT
}  // namespace vanilla

// Perk layout (build_v03 ID_MAIN_PERK / ID_BRANCH_PERK, plan_trees MAIN_MAX_RANK / MAX_BRANCH).
inline constexpr std::uint32_t kMainPerkBase = 0x4000;
inline constexpr std::uint32_t kBranchPerkBase = 0x2000;
inline constexpr int kMainMaxRank = 15;
inline constexpr int kBranchSlots = 4;

// Node slots the DLL reads, looked up by v0.4 name (NODE_IDENTITY in fix19_native.py, build/fix21_identity.py).
namespace node {
inline constexpr NodeId kEarthStaminaCut{3, 0, 2};  // v0.4 earth 命中削減目標耐力
inline constexpr BranchId kEarthDrainStrength{3, 0, 2, 0};  // v0.4 earth 汲力
inline constexpr BranchId kWindTailwind{4, 0, 1, 1};  // v0.4 wind 順風
inline constexpr BranchId kBloodOverflow{5, 0, 1, 1};  // v0.4 blood 血溢
inline constexpr NodeId kBloodLeechRatio{5, 0, 2};  // v0.4 blood 吸血比例各血位
inline constexpr BranchId kBloodReverse{5, 0, 2, 0};  // v0.4 blood 逆流
inline constexpr BranchId kBloodRage{5, 0, 3, 1};  // v0.4 blood 血怒
inline constexpr BranchId kDivineExorcism{6, 0, 0, 1};  // v0.4 divine 驅魔
inline constexpr BranchId kWaterClearStream{8, 0, 0, 0};  // v0.4 water 清流
inline constexpr NodeId kWaterSoakDuration{8, 0, 0};  // v0.4 water 浸濕持續
inline constexpr NodeId kCommonStage2{12, 0, 1};  // v0.4 common 同調二段時附傷
inline constexpr NodeId kCommonStage3Power{12, 0, 3};  // v0.4 common 同調三段時重擊附傷
inline constexpr NodeId kCommonAll1{12, 1, 0};  // v0.4 common 所有元素附傷
inline constexpr NodeId kCommonAll2{12, 1, 3};  // v0.4 common 所有元素附傷再
inline constexpr BranchId kCommonEcho{12, 2, 0, 0};  // v0.4 common 餘響
inline constexpr NodeId kCommonEchoRatio{12, 2, 2};  // v0.4 common 切換後首次命中附帶前一元素附傷
inline constexpr NodeId kNoFormSiphonAmount{11, 0, 0};  // v0.4 noform 吸魔量
inline constexpr BranchId kNoFormRiposte{11, 0, 1, 0};  // v0.4 noform 反擊
inline constexpr NodeId kNoFormDispelRate{11, 1, 0};  // v0.4 noform 滅法倍率
inline constexpr BranchId kNoFormSeize{11, 1, 0, 0};  // v0.4 noform 奪魔
inline constexpr NodeId kNoFormBurnMultiple{11, 1, 1};  // v0.4 noform 燒魔倍數
inline constexpr NodeId kNoFormSilence{11, 1, 2};  // v0.4 noform 沉默
inline constexpr BranchId kNoFormDepletion{11, 1, 2, 0};  // v0.4 noform 枯竭
inline constexpr BranchId kNoFormStillness{11, 1, 2, 1};  // v0.4 noform 靜寂
inline constexpr NodeId kNoFormBurnCasters{11, 1, 3};  // v0.4 noform 對施法者與帶魔法護盾、元素披風的敵人燒魔
inline constexpr NodeId kNoFormLowMagicka{11, 1, 4};  // v0.4 noform 目標魔力低於 25% 時命中傷害
inline constexpr BranchId kNoFormDevour{11, 1, 4, 1};  // v0.4 noform 噬命
inline constexpr BranchId kNoFormHushBreak{11, 2, 1, 2};  // v0.4 noform 寂滅
inline constexpr NodeId kProcAdept[12] = {kNoNode, {0, 0, 1}, {1, 0, 1}, {2, 0, 1}, {3, 0, 1}, {4, 0, 1}, {5, 0, 1}, {6, 0, 1}, {7, 0, 1}, kNoNode, {9, 0, 1}, {10, 0, 1}};  // [element]; water has none
inline constexpr NodeId kProcMaster[12] = {kNoNode, {0, 0, 3}, {1, 0, 3}, {2, 0, 3}, {3, 0, 3}, {4, 0, 3}, {5, 0, 3}, {6, 0, 3}, {7, 0, 3}, kNoNode, {9, 0, 3}, {10, 0, 3}};  // [element]; water has none
}  // namespace node

// settings.json element_damage (B_min, B_max per element; [0] unused) and noform_base_true.
inline constexpr float kElementDamage[12][2] = {{0.0f, 0.0f}, {10.0f, 12.0f}, {8.0f, 10.0f}, {1.0f, 25.0f}, {8.0f, 10.0f}, {8.0f, 9.0f}, {8.0f, 10.0f}, {8.0f, 10.0f}, {8.0f, 9.0f}, {5.0f, 7.0f}, {8.0f, 10.0f}, {8.0f, 10.0f}};
inline constexpr float kNoFormBaseTrue = 5.0f;
inline constexpr std::string_view elementNames[12] = {"無元素", "火焰", "冰霜", "雷電", "大地", "風", "鮮血", "神聖", "毒素", "水", "黑暗", "星界"};
inline constexpr char nativeVersion[] = "0.21.0";
inline constexpr char addressHash[] = "1d7530d001139ca58f462ea0210a8055868159057ba8b5ebc624fc5e9c4f5e9a";
}  // namespace essb
