Scriptname ESSBState Hidden
; Generated by build_v03.py. Change lifetime constants there only.

Quest Function ControllerQuest() Global
	Return Game.GetFormFromFile(0x00600A, "Elements Spellblade.esp") as Quest
EndFunction

Bool Function Operational() Global
	Quest currentQuest = ControllerQuest()
	If !currentQuest
		Return False
	EndIf
	ESSBController ctl = currentQuest.GetAlias(0) as ESSBController
	Return ctl && ctl.IsOperational()
EndFunction

Float Function KillAttributionSeconds() Global
	Return 3.0
EndFunction

Spell Function GuardWindowSpell(Int aiIndex) Global
	If aiIndex < 0 || aiIndex >= 9
		Return None
	EndIf
	Return Game.GetFormFromFile(0x005171 + aiIndex * 2, "Elements Spellblade.esp") as Spell
EndFunction

Int Function BleedSeconds() Global
	Return 10
EndFunction

Int Function PoisonSeconds() Global
	Return 12
EndFunction

Int Function IntCount() Global
	Return 38
EndFunction

Int Function PoisonOffset() Global
	Return 18
EndFunction

Int Function TailOffset() Global
	Return 30
EndFunction

Int[] Function NewBleed() Global
	Int[] result = new Int[10]
	Return result
EndFunction

Int[] Function NewPoison() Global
	Int[] result = new Int[12]
	Return result
EndFunction

Int[] Function NewInts() Global
	Int[] result = new Int[38]
	Return result
EndFunction

Int[] Function NewBackup() Global
	Int[] result = new Int[76]
	Return result
EndFunction

Int[] Function UpgradeInts(Int[] old) Global
	If !old || old.Length != 27
		Return old
	EndIf
	Int[] result = NewInts()
	Int i = 0
	While i < 13
		result[i] = old[i]
		i += 1
	EndWhile
	i = 0
	While i < 6
		result[PoisonOffset() + i] = old[13 + i]
		i += 1
	EndWhile
	i = 0
	While i < 8
		result[TailOffset() + i] = old[19 + i]
		i += 1
	EndWhile
	Return result
EndFunction
; Generated MCM defaults: same rows as config.json and its GLOB equality gate.
Function RestoreTunableDefaults() Global
	GlobalVariable knob
	knob = Game.GetFormFromFile(0x005158, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(0.21164021164021163)
	knob = Game.GetFormFromFile(0x005159, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(0.11428571428571428)
	knob = Game.GetFormFromFile(0x00515A, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00515C, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(3.0)
	knob = Game.GetFormFromFile(0x005168, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x005169, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516A, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516B, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516C, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516D, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
EndFunction
