Scriptname ESSBState Hidden
; Generated by build_v03.py. Change the constants there only.

Quest Function ControllerQuest() Global
	Return Game.GetFormFromFile(0x006016, "Elements Spellblade.esp") as Quest
EndFunction

Bool Function Operational() Global
	Quest currentQuest = ControllerQuest()
	If !currentQuest
		Return False
	EndIf
	ESSBController ctl = currentQuest.GetAlias(0) as ESSBController
	Return ctl && ctl.IsOperational()
EndFunction

Bool Function ReadyUI() Global
	Quest currentQuest = ControllerQuest()
	If !currentQuest
		Return False
	EndIf
	ESSBController ctl = currentQuest.GetAlias(0) as ESSBController
	Return ctl && ctl.IsReadyUI()
EndFunction

Float Function KillAttributionSeconds() Global
	Return 3.0
EndFunction

Spell Function GuardWindowSpell(Int aiIndex) Global
	If aiIndex < 0 || aiIndex >= 9
		Return None
	EndIf
	Return Game.GetFormFromFile(0x005171 + aiIndex * 2, "Elements Spellblade.esp") as Spell
EndFunction
; Generated MCM defaults: same rows as config.json and its GLOB equality gate.
Function RestoreTunableDefaults() Global
	GlobalVariable knob
	knob = Game.GetFormFromFile(0x005158, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(0.21164021164021163)
	knob = Game.GetFormFromFile(0x005159, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(0.11428571428571428)
	knob = Game.GetFormFromFile(0x00515A, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00515C, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(3.0)
	knob = Game.GetFormFromFile(0x005168, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x005169, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516A, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516B, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516C, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
	knob = Game.GetFormFromFile(0x00516D, "Elements Spellblade.esp") as GlobalVariable
	knob.SetValue(1.0)
EndFunction
